/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.da.qlf0.view.GUI_ThemBN;

import com.da.qlf0.bean.DanhMucThemBN;
import com.da.qlf0.controller.ChuyenMH_ThemBN;
import java.util.ArrayList;

/**
 *
 * @author Minh Cuong
 */
public class ThemBN_Frame extends javax.swing.JFrame {

    /**
     * Creates new form ThemBN_Frame
     */
    public ThemBN_Frame() {
        initComponents();
        ChuyenMH_ThemBN controller = new ChuyenMH_ThemBN(jpnView);
        controller.setView(jpnTTCoBan,jlbTTCoBan);
        
        ArrayList<DanhMucThemBN> listItem = new ArrayList<>();
        listItem.add(new DanhMucThemBN("ThongTinCoBan",jpnTTCoBan,jlbTTCoBan));
        listItem.add(new DanhMucThemBN("TiemVX",jpnTiemVX,jlbTiemVX));
        listItem.add(new DanhMucThemBN("BenhNen",jpnBenhNen2,jlbBenhNen));
        listItem.add(new DanhMucThemBN("TinhTrang",jpnTinhTrang,jlbTinhTrang));
        
        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnTTCoBan = new javax.swing.JPanel();
        jlbTTCoBan = new javax.swing.JLabel();
        jpnTinhTrang = new javax.swing.JPanel();
        jlbTinhTrang = new javax.swing.JLabel();
        jpnTiemVX = new javax.swing.JPanel();
        jlbTiemVX = new javax.swing.JLabel();
        jpnBenhNen2 = new javax.swing.JPanel();
        jlbBenhNen = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 115, 153));
        jLabel1.setText("<<BACK");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jpnTTCoBan.setBackground(new java.awt.Color(0, 180, 153));

        jlbTTCoBan.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jlbTTCoBan.setText("Thông tin cơ bản");

        javax.swing.GroupLayout jpnTTCoBanLayout = new javax.swing.GroupLayout(jpnTTCoBan);
        jpnTTCoBan.setLayout(jpnTTCoBanLayout);
        jpnTTCoBanLayout.setHorizontalGroup(
            jpnTTCoBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTTCoBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTTCoBan)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jpnTTCoBanLayout.setVerticalGroup(
            jpnTTCoBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTTCoBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTTCoBan, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnTinhTrang.setBackground(new java.awt.Color(0, 180, 153));

        jlbTinhTrang.setText("jLabel2");

        javax.swing.GroupLayout jpnTinhTrangLayout = new javax.swing.GroupLayout(jpnTinhTrang);
        jpnTinhTrang.setLayout(jpnTinhTrangLayout);
        jpnTinhTrangLayout.setHorizontalGroup(
            jpnTinhTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTinhTrangLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jlbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jpnTinhTrangLayout.setVerticalGroup(
            jpnTinhTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTinhTrangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTinhTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnTiemVX.setBackground(new java.awt.Color(0, 180, 153));

        jlbTiemVX.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jlbTiemVX.setText("Tiêm Vắc xin");

        javax.swing.GroupLayout jpnTiemVXLayout = new javax.swing.GroupLayout(jpnTiemVX);
        jpnTiemVX.setLayout(jpnTiemVXLayout);
        jpnTiemVXLayout.setHorizontalGroup(
            jpnTiemVXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTiemVXLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jlbTiemVX, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jpnTiemVXLayout.setVerticalGroup(
            jpnTiemVXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTiemVXLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTiemVX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnBenhNen2.setBackground(new java.awt.Color(0, 180, 153));

        jlbBenhNen.setText("jLabel2");

        javax.swing.GroupLayout jpnBenhNen2Layout = new javax.swing.GroupLayout(jpnBenhNen2);
        jpnBenhNen2.setLayout(jpnBenhNen2Layout);
        jpnBenhNen2Layout.setHorizontalGroup(
            jpnBenhNen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBenhNen2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jlbBenhNen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jpnBenhNen2Layout.setVerticalGroup(
            jpnBenhNen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBenhNen2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbBenhNen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jpnTTCoBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnTiemVX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnBenhNen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(617, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpnBenhNen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnTiemVX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnTTCoBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnTinhTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
                this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemBN_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemBN_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemBN_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemBN_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemBN_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbBenhNen;
    private javax.swing.JLabel jlbTTCoBan;
    private javax.swing.JLabel jlbTiemVX;
    private javax.swing.JLabel jlbTinhTrang;
    private javax.swing.JPanel jpnBenhNen;
    private javax.swing.JPanel jpnBenhNen1;
    private javax.swing.JPanel jpnBenhNen2;
    private javax.swing.JPanel jpnTTCoBan;
    private javax.swing.JPanel jpnTiemVX;
    private javax.swing.JPanel jpnTinhTrang;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}
