/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.da.qlf0.view.GUI_ThemBN;

import com.toedter.calendar.JDateChooser;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;

/**
 *
 * @author Minh Cuong
 */
public class TiemVX_ThemBN extends javax.swing.JPanel {

    /**
     * Creates new form TTCoBan_ThemBN
     */
    public TiemVX_ThemBN() {
        initComponents();
        
    }

    public JComboBox<String> getJcobLoaiVX1() {
        return jcobLoaiVX1;
    }

    public JComboBox<String> getJcobLoaiVX2() {
        return jcobLoaiVX2;
    }

    public JComboBox<String> getJcobLoaiVX3() {
        return jcobLoaiVX3;
    }

    public JDateChooser getJdcTGTiem1() {
        return jdcTGTiem1;
    }

    public JDateChooser getJdcTGTiem2() {
        return jdcTGTiem2;
    }

    public JDateChooser getJdcTGTiem3() {
        return jdcTGTiem3;
    }

    public JRadioButton getJrbTiemVX_1m() {
        return jrbTiemVX_1m;
    }

    public JRadioButton getJrbTiemVX_2m() {
        return jrbTiemVX_2m;
    }

    public JRadioButton getJrbTiemVX_3m() {
        return jrbTiemVX_3m;
    }

    public JRadioButton getJrbTiemVX_ChuaTiem() {
        return jrbTiemVX_ChuaTiem;
    }

    public JRadioButton getJrbTiemVX_KhongBiet() {
        return jrbTiemVX_KhongBiet;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnG_MuiTiem = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jrbTiemVX_ChuaTiem = new javax.swing.JRadioButton();
        jrbTiemVX_1m = new javax.swing.JRadioButton();
        jrbTiemVX_3m = new javax.swing.JRadioButton();
        jrbTiemVX_2m = new javax.swing.JRadioButton();
        jrbTiemVX_KhongBiet = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jcobLoaiVX1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jdcTGTiem1 = new com.toedter.calendar.JDateChooser();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcobLoaiVX2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jdcTGTiem2 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jcobLoaiVX3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jdcTGTiem3 = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(20, 20, 20));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(20, 20, 20));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 41, 102));
        jLabel9.setText("Mũi 1");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(20, 20, 20));
        jLabel12.setText(" Tình trạng tiêm Vắc xin:");

        jrbTiemVX_ChuaTiem.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MuiTiem.add(jrbTiemVX_ChuaTiem);
        jrbTiemVX_ChuaTiem.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbTiemVX_ChuaTiem.setForeground(new java.awt.Color(20, 20, 20));
        jrbTiemVX_ChuaTiem.setText("Chưa tiêm");
        jrbTiemVX_ChuaTiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTiemVX_ChuaTiemActionPerformed(evt);
            }
        });

        jrbTiemVX_1m.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MuiTiem.add(jrbTiemVX_1m);
        jrbTiemVX_1m.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbTiemVX_1m.setForeground(new java.awt.Color(20, 20, 20));
        jrbTiemVX_1m.setText("1 Mũi");
        jrbTiemVX_1m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTiemVX_1mActionPerformed(evt);
            }
        });

        jrbTiemVX_3m.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MuiTiem.add(jrbTiemVX_3m);
        jrbTiemVX_3m.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbTiemVX_3m.setForeground(new java.awt.Color(20, 20, 20));
        jrbTiemVX_3m.setText("3 Mũi");
        jrbTiemVX_3m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTiemVX_3mActionPerformed(evt);
            }
        });

        jrbTiemVX_2m.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MuiTiem.add(jrbTiemVX_2m);
        jrbTiemVX_2m.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbTiemVX_2m.setForeground(new java.awt.Color(20, 20, 20));
        jrbTiemVX_2m.setText("2 Mũi");
        jrbTiemVX_2m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTiemVX_2mActionPerformed(evt);
            }
        });

        jrbTiemVX_KhongBiet.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MuiTiem.add(jrbTiemVX_KhongBiet);
        jrbTiemVX_KhongBiet.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbTiemVX_KhongBiet.setForeground(new java.awt.Color(20, 20, 20));
        jrbTiemVX_KhongBiet.setText("Không biết");
        jrbTiemVX_KhongBiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTiemVX_KhongBietActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(166, 166, 166));

        jcobLoaiVX1.setBackground(new java.awt.Color(255, 255, 255));
        jcobLoaiVX1.setForeground(new java.awt.Color(20, 20, 20));
        jcobLoaiVX1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AstraZeneca", "Sputnik V", "VeroCell", "Pfizer", "Moderna", "Janssen", "Covaxin" }));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(20, 20, 20));
        jLabel1.setText("Thời gian tiêm: *");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 20, 20));
        jLabel2.setText("Loại Vắc xin 1: *");

        jdcTGTiem1.setBackground(new java.awt.Color(255, 255, 255));
        jdcTGTiem1.setForeground(new java.awt.Color(20, 20, 20));
        jdcTGTiem1.setDateFormatString("dd-MM-yyyy\n\n");
        jdcTGTiem1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jSeparator5.setBackground(new java.awt.Color(166, 166, 166));

        jSeparator6.setBackground(new java.awt.Color(166, 166, 166));

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 41, 102));
        jLabel11.setText("Mũi 2");

        jSeparator7.setBackground(new java.awt.Color(166, 166, 166));

        jSeparator4.setBackground(new java.awt.Color(166, 166, 166));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 1766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel12)
                            .addGap(75, 75, 75)
                            .addComponent(jrbTiemVX_ChuaTiem)
                            .addGap(60, 60, 60)
                            .addComponent(jrbTiemVX_1m)
                            .addGap(83, 83, 83)
                            .addComponent(jrbTiemVX_2m)
                            .addGap(73, 73, 73)
                            .addComponent(jrbTiemVX_3m)
                            .addGap(60, 60, 60)
                            .addComponent(jrbTiemVX_KhongBiet))
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1766, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addComponent(jLabel9))
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 1766, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addComponent(jLabel2)
                            .addGap(93, 93, 93)
                            .addComponent(jcobLoaiVX1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(170, 170, 170)
                            .addComponent(jLabel1)
                            .addGap(119, 119, 119)
                            .addComponent(jdcTGTiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addComponent(jLabel11))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jrbTiemVX_ChuaTiem)
                    .addComponent(jrbTiemVX_1m)
                    .addComponent(jrbTiemVX_2m)
                    .addComponent(jrbTiemVX_3m)
                    .addComponent(jrbTiemVX_KhongBiet))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jcobLoaiVX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jdcTGTiem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(null);

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(20, 20, 20));
        jLabel7.setText("TIÊM VẮC XIN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(630, 630, 630)
                .addComponent(jLabel7)
                .addContainerGap(988, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 41, 102));
        jLabel8.setText("TIÊM VẮC XIN PHÒNG COVID-19");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(20, 20, 20));
        jLabel3.setText("Loại Vắc xin 2: *");

        jcobLoaiVX2.setBackground(new java.awt.Color(255, 255, 255));
        jcobLoaiVX2.setForeground(new java.awt.Color(20, 20, 20));
        jcobLoaiVX2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AstraZeneca", "Sputnik V", "VeroCell", "Pfizer", "Moderna", "Janssen", "Covaxin" }));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(20, 20, 20));
        jLabel4.setText("Thời gian tiêm: *");

        jdcTGTiem2.setBackground(new java.awt.Color(255, 255, 255));
        jdcTGTiem2.setForeground(new java.awt.Color(20, 20, 20));
        jdcTGTiem2.setDateFormatString("dd-MM-yyyy\n\n");

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 41, 102));
        jLabel13.setText("Mũi 3");

        jSeparator8.setBackground(new java.awt.Color(166, 166, 166));

        jSeparator9.setBackground(new java.awt.Color(166, 166, 166));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(20, 20, 20));
        jLabel5.setText("Loại Vắc xin 3: *");

        jcobLoaiVX3.setBackground(new java.awt.Color(255, 255, 255));
        jcobLoaiVX3.setForeground(new java.awt.Color(20, 20, 20));
        jcobLoaiVX3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AstraZeneca", "Sputnik V", "VeroCell", "Pfizer", "Moderna", "Janssen", "Covaxin", " " }));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(20, 20, 20));
        jLabel6.setText("Thời gian tiêm : *");

        jdcTGTiem3.setBackground(new java.awt.Color(255, 255, 255));
        jdcTGTiem3.setForeground(new java.awt.Color(20, 20, 20));
        jdcTGTiem3.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel3)
                                .addGap(102, 102, 102)
                                .addComponent(jcobLoaiVX2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163)
                                .addComponent(jLabel4)
                                .addGap(128, 128, 128)
                                .addComponent(jdcTGTiem2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel5)
                                .addGap(107, 107, 107)
                                .addComponent(jcobLoaiVX3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(165, 165, 165)
                                .addComponent(jLabel6)
                                .addGap(128, 128, 128)
                                .addComponent(jdcTGTiem3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 83, Short.MAX_VALUE))
                            .addComponent(jSeparator8))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jcobLoaiVX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jdcTGTiem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcobLoaiVX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jdcTGTiem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrbTiemVX_KhongBietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTiemVX_KhongBietActionPerformed
        // TODO add your handling code here:
         jcobLoaiVX1.setEnabled(false);
        jcobLoaiVX2.setEnabled(false);
        jcobLoaiVX3.setEnabled(false);
        
//         jcobLoaiVX1.setSelectedItem(null);
//        jcobLoaiVX2.setSelectedItem(null);
//        jcobLoaiVX3.setSelectedItem(null);
    }//GEN-LAST:event_jrbTiemVX_KhongBietActionPerformed

    private void jrbTiemVX_ChuaTiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTiemVX_ChuaTiemActionPerformed
        // TODO add your handling code here:
        jcobLoaiVX1.setEnabled(false);
        jcobLoaiVX2.setEnabled(false);
        jcobLoaiVX3.setEnabled(false);
        
//        jcobLoaiVX1.setSelectedItem(null);
//        jcobLoaiVX2.setSelectedItem(null);
//        jcobLoaiVX3.setSelectedItem(null);
        
        jdcTGTiem1.setEnabled(false);
    }//GEN-LAST:event_jrbTiemVX_ChuaTiemActionPerformed

    private void jrbTiemVX_1mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTiemVX_1mActionPerformed
        // TODO add your handling code here:
        jcobLoaiVX1.setEnabled(true);
        jcobLoaiVX2.setEnabled(false);
        jcobLoaiVX3.setEnabled(false);
        
//         jcobLoaiVX2.setSelectedItem(null);
//        jcobLoaiVX3.setSelectedItem(null);
    }//GEN-LAST:event_jrbTiemVX_1mActionPerformed

    private void jrbTiemVX_2mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTiemVX_2mActionPerformed
        // TODO add your handling code here:
        jcobLoaiVX1.setEnabled(true);
        jcobLoaiVX2.setEnabled(true);
        jcobLoaiVX3.setEnabled(false);
//         jcobLoaiVX3.setSelectedItem(null);
       
    }//GEN-LAST:event_jrbTiemVX_2mActionPerformed

    private void jrbTiemVX_3mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTiemVX_3mActionPerformed
        // TODO add your handling code here:
        jcobLoaiVX1.setEnabled(true);
        jcobLoaiVX2.setEnabled(true);
        jcobLoaiVX3.setEnabled(true);
    }//GEN-LAST:event_jrbTiemVX_3mActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnG_MuiTiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JComboBox<String> jcobLoaiVX1;
    private javax.swing.JComboBox<String> jcobLoaiVX2;
    private javax.swing.JComboBox<String> jcobLoaiVX3;
    private com.toedter.calendar.JDateChooser jdcTGTiem1;
    private com.toedter.calendar.JDateChooser jdcTGTiem2;
    private com.toedter.calendar.JDateChooser jdcTGTiem3;
    private javax.swing.JRadioButton jrbTiemVX_1m;
    private javax.swing.JRadioButton jrbTiemVX_2m;
    private javax.swing.JRadioButton jrbTiemVX_3m;
    private javax.swing.JRadioButton jrbTiemVX_ChuaTiem;
    private javax.swing.JRadioButton jrbTiemVX_KhongBiet;
    // End of variables declaration//GEN-END:variables
}
