/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.da.qlf0.view.GUI_ThemBN;

import com.toedter.calendar.JDateChooser;

import java.awt.event.ActionListener;
import javax.swing.Action;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import com.da.qlf0.controller.LayMABNTuDong;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Minh Cuong
 */
public class TTCoBan_ThemBN extends javax.swing.JPanel {

    /**
     * Creates new form TTCoBan_ThemBN
     */
    public TTCoBan_ThemBN() {
        initComponents();
        MyinnitsetMBBN();
       
        
        
    }

    public JCheckBox getJcbNam() {
        return jcbNam;
    }

    public JCheckBox getJcbNu() {
        return jcbNu;
    }

    public JCheckBox getJcbTestNhanh_Co() {
        return jcbTestNhanh_Co;
    }

    public JCheckBox getJcbTestNhanh_Khong() {
        return jcbTestNhanh_Khong;
    }

    public JCheckBox getJcbTestPCR_Co() {
        return jcbTestPCR_Co;
    }

    public JCheckBox getJcbTestPCR_Khong() {
        return jcbTestPCR_Khong;
    }

    public JCheckBox getJcbTungLaF0_Co() {
        return jcbTungLaF0_Co;
    }

    public JCheckBox getJcbTungLaF0_Khong() {
        return jcbTungLaF0_Khong;
    }

    public JComboBox<String> getJcobPhuong_Xa() {
        return jcobPhuong_Xa;
    }

    public JComboBox<String> getJcobQuan_Huyen() {
        return jcobQuan_Huyen;
    }

    public JComboBox<String> getJcobTinh_ThanhPho() {
        return jcobTinh_ThanhPho;
    }

    public JDateChooser getJdcNgaySinh() {
        return jdcNgaySinh;
    }

    public JDateChooser getJdcNgayTestNhanh() {
        return jdcNgayTestNhanh;
    }

    public JDateChooser getJdcNgayTestPCR() {
        return jdcNgayTestPCR;
    }

    public JDateChooser getJdcNgayTnF0() {
        return jdcNgayTnF0;
    }

    public JDateChooser getJdcNgayXHTTDT() {
        return jdcNgayXHTTDT;
    }

    public JTextField getJtfCMND_CCCD() {
        return jtfCMND_CCCD;
    }

    public JTextField getJtfHoTen() {
        return jtfHoTen;
    }

    public JTextField getJtfMABN() {
        return jtfMABN;
    }

    public JTextField getJtfNgheNghiep() {
        return jtfNgheNghiep;
    }

    public JTextField getJtfNoiLamViec() {
        return jtfNoiLamViec;
    }

    public JTextField getJtfNoiO() {
        return jtfNoiO;
    }

    public JTextField getJtfSDT() {
        return jtfSDT;
    }

    public JTextField getJtfSoThangF0() {
        return jtfSoThangF0;
    }

    public JComboBox<String> getJcobKQTestNhanh() {
        return jcobKQTestNhanh;
    }

    public JComboBox<String> getJcobKQTestPCR() {
        return jcobKQTestPCR;
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnG_GioiTinh = new javax.swing.ButtonGroup();
        btnG_TunglaF0 = new javax.swing.ButtonGroup();
        btnG_TestNhanh = new javax.swing.ButtonGroup();
        btnG_RTPCR = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbHoTen = new javax.swing.JLabel();
        jtfHoTen = new javax.swing.JTextField();
        jlbNgheNghiep = new javax.swing.JLabel();
        jtfNgheNghiep = new javax.swing.JTextField();
        jlbTinh_ThanhPho = new javax.swing.JLabel();
        jcobTinh_ThanhPho = new javax.swing.JComboBox<>();
        jlbQuan_Huyen = new javax.swing.JLabel();
        jcobQuan_Huyen = new javax.swing.JComboBox<>();
        jlbCMND_CCCD = new javax.swing.JLabel();
        jtfCMND_CCCD = new javax.swing.JTextField();
        jlbNgayTiepNhan = new javax.swing.JLabel();
        jlbGioiTinh = new javax.swing.JLabel();
        jdcNgayTnF0 = new com.toedter.calendar.JDateChooser();
        jcbTungLaF0_Co = new javax.swing.JCheckBox();
        jcbNu = new javax.swing.JCheckBox();
        jlbTungLaF0 = new javax.swing.JLabel();
        jcbNam = new javax.swing.JCheckBox();
        jcbTungLaF0_Khong = new javax.swing.JCheckBox();
        jlbTestNhanh = new javax.swing.JLabel();
        jlbRT_PCR = new javax.swing.JLabel();
        jcbTestNhanh_Co = new javax.swing.JCheckBox();
        jcbTestNhanh_Khong = new javax.swing.JCheckBox();
        jcbTestPCR_Co = new javax.swing.JCheckBox();
        jcbTestPCR_Khong = new javax.swing.JCheckBox();
        jlbMABN = new javax.swing.JLabel();
        jtfMABN = new javax.swing.JTextField();
        jlbNgaySinh = new javax.swing.JLabel();
        jdcNgaySinh = new com.toedter.calendar.JDateChooser();
        jlbNoiO = new javax.swing.JLabel();
        jtfSDT = new javax.swing.JTextField();
        jlbPhuong_Xa = new javax.swing.JLabel();
        jcobPhuong_Xa = new javax.swing.JComboBox<>();
        jlbNoiLamViec = new javax.swing.JLabel();
        jtfNoiO = new javax.swing.JTextField();
        jlbSĐT = new javax.swing.JLabel();
        jtfNoiLamViec = new javax.swing.JTextField();
        jlbSoThangLaF0 = new javax.swing.JLabel();
        jtfSoThangF0 = new javax.swing.JTextField();
        jlbNgayXHTTDT = new javax.swing.JLabel();
        jdcNgayTestPCR = new com.toedter.calendar.JDateChooser();
        jlbNgayTestNhanh = new javax.swing.JLabel();
        jdcNgayXHTTDT = new com.toedter.calendar.JDateChooser();
        jlbNgayTestPCR = new javax.swing.JLabel();
        jdcNgayTestNhanh = new com.toedter.calendar.JDateChooser();
        jlbTestNhanh1 = new javax.swing.JLabel();
        jcobKQTestNhanh = new javax.swing.JComboBox<>();
        jlbTestNhanh2 = new javax.swing.JLabel();
        jcobKQTestPCR = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(20, 20, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(null);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(20, 20, 20));
        jLabel1.setText("THÔNG TIN NGƯỜI BỆNH");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlbHoTen.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbHoTen.setForeground(new java.awt.Color(20, 20, 20));
        jlbHoTen.setText("Họ và tên *");

        jtfHoTen.setBackground(new java.awt.Color(255, 255, 255));
        jtfHoTen.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfHoTen.setForeground(new java.awt.Color(20, 20, 20));
        jtfHoTen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfHoTenActionPerformed(evt);
            }
        });

        jlbNgheNghiep.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbNgheNghiep.setForeground(new java.awt.Color(20, 20, 20));
        jlbNgheNghiep.setText("Nghề nghiệp");

        jtfNgheNghiep.setBackground(new java.awt.Color(255, 255, 255));
        jtfNgheNghiep.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfNgheNghiep.setForeground(new java.awt.Color(20, 20, 20));
        jtfNgheNghiep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfNgheNghiep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNgheNghiepActionPerformed(evt);
            }
        });

        jlbTinh_ThanhPho.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbTinh_ThanhPho.setForeground(new java.awt.Color(20, 20, 20));
        jlbTinh_ThanhPho.setText("Tỉnh/Thành phố *");

        jcobTinh_ThanhPho.setBackground(new java.awt.Color(255, 255, 255));
        jcobTinh_ThanhPho.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jcobTinh_ThanhPho.setForeground(new java.awt.Color(20, 20, 20));
        jcobTinh_ThanhPho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hồ Chí Minh", "Đà Nẵng ", "Bình Dương", "Cần Thơ", "Đồng tháp", "Hà Nội", "Thanh Hóa", "Thái Bình", "An Giang", " " }));
        jcobTinh_ThanhPho.setBorder(null);
        jcobTinh_ThanhPho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcobTinh_ThanhPhoActionPerformed(evt);
            }
        });

        jlbQuan_Huyen.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbQuan_Huyen.setForeground(new java.awt.Color(20, 20, 20));
        jlbQuan_Huyen.setText("Quận/Huyện *");

        jcobQuan_Huyen.setBackground(new java.awt.Color(255, 255, 255));
        jcobQuan_Huyen.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jcobQuan_Huyen.setForeground(new java.awt.Color(20, 20, 20));
        jcobQuan_Huyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quận 1", "Quận 3", "Quận 4", "Quận 5", "Quận 6", "Quận 7", "Quận 8", "Quận 9", "Quận 10", "Quận 11", "Quận 12", "Bình Thạnh", "Gò Vấp", "Tân Phú", "Cần Giờ", "Củ Chi", "Hóc Môn", "Nhà Bè" }));
        jcobQuan_Huyen.setBorder(null);
        jcobQuan_Huyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcobQuan_HuyenActionPerformed(evt);
            }
        });

        jlbCMND_CCCD.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbCMND_CCCD.setForeground(new java.awt.Color(20, 20, 20));
        jlbCMND_CCCD.setText("CMND/CCCD *");

        jtfCMND_CCCD.setBackground(new java.awt.Color(255, 255, 255));
        jtfCMND_CCCD.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfCMND_CCCD.setForeground(new java.awt.Color(20, 20, 20));
        jtfCMND_CCCD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfCMND_CCCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCMND_CCCDActionPerformed(evt);
            }
        });
        jtfCMND_CCCD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCMND_CCCDKeyPressed(evt);
            }
        });

        jlbNgayTiepNhan.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbNgayTiepNhan.setForeground(new java.awt.Color(20, 20, 20));
        jlbNgayTiepNhan.setText("Ngày tiếp nhận F0 *");

        jlbGioiTinh.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbGioiTinh.setForeground(new java.awt.Color(20, 20, 20));
        jlbGioiTinh.setText("Giới Tính *");

        jdcNgayTnF0.setDateFormatString("dd-MM-yyyy\n");

        btnG_TunglaF0.add(jcbTungLaF0_Co);
        jcbTungLaF0_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jcbTungLaF0_Co.setForeground(new java.awt.Color(20, 20, 20));
        jcbTungLaF0_Co.setText("Có ");
        jcbTungLaF0_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTungLaF0_CoActionPerformed(evt);
            }
        });

        btnG_GioiTinh.add(jcbNu);
        jcbNu.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jcbNu.setForeground(new java.awt.Color(20, 20, 20));
        jcbNu.setText("Nữ");
        jcbNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNuActionPerformed(evt);
            }
        });

        jlbTungLaF0.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbTungLaF0.setForeground(new java.awt.Color(20, 20, 20));
        jlbTungLaF0.setText("Từng là F0 *");

        btnG_GioiTinh.add(jcbNam);
        jcbNam.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jcbNam.setForeground(new java.awt.Color(20, 20, 20));
        jcbNam.setText("Nam");
        jcbNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNamActionPerformed(evt);
            }
        });

        btnG_TunglaF0.add(jcbTungLaF0_Khong);
        jcbTungLaF0_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jcbTungLaF0_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jcbTungLaF0_Khong.setText("Không");
        jcbTungLaF0_Khong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTungLaF0_KhongActionPerformed(evt);
            }
        });

        jlbTestNhanh.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbTestNhanh.setForeground(new java.awt.Color(20, 20, 20));
        jlbTestNhanh.setText("Test Nhanh *");

        jlbRT_PCR.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbRT_PCR.setForeground(new java.awt.Color(20, 20, 20));
        jlbRT_PCR.setText("RT-PCR *");

        btnG_TestNhanh.add(jcbTestNhanh_Co);
        jcbTestNhanh_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jcbTestNhanh_Co.setForeground(new java.awt.Color(20, 20, 20));
        jcbTestNhanh_Co.setText("Có ");
        jcbTestNhanh_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTestNhanh_CoActionPerformed(evt);
            }
        });

        btnG_TestNhanh.add(jcbTestNhanh_Khong);
        jcbTestNhanh_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jcbTestNhanh_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jcbTestNhanh_Khong.setText("Không");
        jcbTestNhanh_Khong.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jcbTestNhanh_KhongStateChanged(evt);
            }
        });
        jcbTestNhanh_Khong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTestNhanh_KhongActionPerformed(evt);
            }
        });

        btnG_RTPCR.add(jcbTestPCR_Co);
        jcbTestPCR_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jcbTestPCR_Co.setForeground(new java.awt.Color(20, 20, 20));
        jcbTestPCR_Co.setText("Có ");
        jcbTestPCR_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTestPCR_CoActionPerformed(evt);
            }
        });

        btnG_RTPCR.add(jcbTestPCR_Khong);
        jcbTestPCR_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jcbTestPCR_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jcbTestPCR_Khong.setText("Không");
        jcbTestPCR_Khong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTestPCR_KhongActionPerformed(evt);
            }
        });

        jlbMABN.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbMABN.setForeground(new java.awt.Color(20, 20, 20));
        jlbMABN.setText("Mã bệnh nhân *");

        jtfMABN.setEditable(false);
        jtfMABN.setBackground(new java.awt.Color(255, 255, 255));
        jtfMABN.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfMABN.setForeground(new java.awt.Color(20, 20, 20));
        jtfMABN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfMABN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMABNActionPerformed(evt);
            }
        });

        jlbNgaySinh.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbNgaySinh.setForeground(new java.awt.Color(20, 20, 20));
        jlbNgaySinh.setText("Ngày sinh *");

        jdcNgaySinh.setBackground(new java.awt.Color(255, 255, 255));
        jdcNgaySinh.setForeground(new java.awt.Color(20, 20, 20));
        jdcNgaySinh.setDateFormatString("dd-MM-yyyy");

        jlbNoiO.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbNoiO.setForeground(new java.awt.Color(20, 20, 20));
        jlbNoiO.setText("Nơi ở hiện tại *");

        jtfSDT.setBackground(new java.awt.Color(255, 255, 255));
        jtfSDT.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfSDT.setForeground(new java.awt.Color(20, 20, 20));
        jtfSDT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSDTActionPerformed(evt);
            }
        });
        jtfSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfSDTKeyPressed(evt);
            }
        });

        jlbPhuong_Xa.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbPhuong_Xa.setForeground(new java.awt.Color(20, 20, 20));
        jlbPhuong_Xa.setText("Phường/Xã *");

        jcobPhuong_Xa.setBackground(new java.awt.Color(255, 255, 255));
        jcobPhuong_Xa.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jcobPhuong_Xa.setForeground(new java.awt.Color(20, 20, 20));
        jcobPhuong_Xa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tân Thới Nhất", "Đông Hưng Thuận", "Trung Mỹ Tây", "Tân Chánh Hiệp", "Tân Thới Hiệp", "Hiệp Thành", "Thới An", "Thạnh Lộc", "Thạnh Xuân", "Tân Hưng Thuận", "An Phú Đông", "Bến Nghé", "Bến Thành", "Cô Giang", "Cầu Kho", "Cầu Ông Lãnh", "Đa Kao", "Nguyễn Cư Trinh", "Nguyễn Thái Bình", "Phạm Ngũ Lão", "Tân Định." }));
        jcobPhuong_Xa.setBorder(null);
        jcobPhuong_Xa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcobPhuong_XaActionPerformed(evt);
            }
        });

        jlbNoiLamViec.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbNoiLamViec.setForeground(new java.awt.Color(20, 20, 20));
        jlbNoiLamViec.setText("Nơi làm việc");

        jtfNoiO.setBackground(new java.awt.Color(255, 255, 255));
        jtfNoiO.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfNoiO.setForeground(new java.awt.Color(20, 20, 20));
        jtfNoiO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfNoiO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNoiOActionPerformed(evt);
            }
        });

        jlbSĐT.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbSĐT.setForeground(new java.awt.Color(20, 20, 20));
        jlbSĐT.setText("Số điện thoại *");

        jtfNoiLamViec.setBackground(new java.awt.Color(255, 255, 255));
        jtfNoiLamViec.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfNoiLamViec.setForeground(new java.awt.Color(20, 20, 20));
        jtfNoiLamViec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfNoiLamViec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNoiLamViecActionPerformed(evt);
            }
        });

        jlbSoThangLaF0.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbSoThangLaF0.setForeground(new java.awt.Color(20, 20, 20));
        jlbSoThangLaF0.setText("Số ngày từng là F0");

        jtfSoThangF0.setBackground(new java.awt.Color(255, 255, 255));
        jtfSoThangF0.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfSoThangF0.setForeground(new java.awt.Color(20, 20, 20));
        jtfSoThangF0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfSoThangF0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSoThangF0ActionPerformed(evt);
            }
        });

        jlbNgayXHTTDT.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbNgayXHTTDT.setForeground(new java.awt.Color(20, 20, 20));
        jlbNgayXHTTDT.setText("Ngày xuất hiện triệu chứng đầu tiên *");

        jdcNgayTestPCR.setBackground(new java.awt.Color(255, 255, 255));
        jdcNgayTestPCR.setForeground(new java.awt.Color(20, 20, 20));
        jdcNgayTestPCR.setDateFormatString("dd-MM-yyyy");

        jlbNgayTestNhanh.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbNgayTestNhanh.setForeground(new java.awt.Color(20, 20, 20));
        jlbNgayTestNhanh.setText("Ngày test nhanh *");

        jdcNgayXHTTDT.setBackground(new java.awt.Color(255, 255, 255));
        jdcNgayXHTTDT.setForeground(new java.awt.Color(20, 20, 20));
        jdcNgayXHTTDT.setDateFormatString("dd-MM-yyyy");

        jlbNgayTestPCR.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbNgayTestPCR.setForeground(new java.awt.Color(20, 20, 20));
        jlbNgayTestPCR.setText("Ngày test RT-PCR *");

        jdcNgayTestNhanh.setBackground(new java.awt.Color(255, 255, 255));
        jdcNgayTestNhanh.setForeground(new java.awt.Color(20, 20, 20));
        jdcNgayTestNhanh.setDateFormatString("dd-MM-yyyy");

        jlbTestNhanh1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbTestNhanh1.setForeground(new java.awt.Color(20, 20, 20));
        jlbTestNhanh1.setText("Kết quả:*");

        jcobKQTestNhanh.setBackground(new java.awt.Color(255, 255, 255));
        jcobKQTestNhanh.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jcobKQTestNhanh.setForeground(new java.awt.Color(20, 20, 20));
        jcobKQTestNhanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Âm tính", "Dương tính", " " }));
        jcobKQTestNhanh.setBorder(null);
        jcobKQTestNhanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcobKQTestNhanhActionPerformed(evt);
            }
        });

        jlbTestNhanh2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlbTestNhanh2.setForeground(new java.awt.Color(20, 20, 20));
        jlbTestNhanh2.setText("Kết quả:*");

        jcobKQTestPCR.setBackground(new java.awt.Color(255, 255, 255));
        jcobKQTestPCR.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jcobKQTestPCR.setForeground(new java.awt.Color(20, 20, 20));
        jcobKQTestPCR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Âm tính", "Dương tính", " " }));
        jcobKQTestPCR.setBorder(null);
        jcobKQTestPCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcobKQTestPCRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbCMND_CCCD)
                            .addComponent(jlbNgheNghiep)
                            .addComponent(jlbQuan_Huyen)
                            .addComponent(jlbTinh_ThanhPho)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlbGioiTinh)
                                .addComponent(jlbHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcbNam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbNu))
                            .addComponent(jcobTinh_ThanhPho, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcobQuan_Huyen, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNgheNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCMND_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbTungLaF0)
                            .addComponent(jlbTestNhanh)
                            .addComponent(jlbRT_PCR)
                            .addComponent(jlbNgayTiepNhan))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdcNgayTnF0, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jcbTungLaF0_Co)
                                    .addComponent(jcbTestNhanh_Co)
                                    .addComponent(jcbTestPCR_Co))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbTungLaF0_Khong)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbTestNhanh_Khong)
                                            .addComponent(jcbTestPCR_Khong))
                                        .addGap(63, 63, 63)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jlbTestNhanh2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jcobKQTestPCR, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jlbTestNhanh1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jcobKQTestNhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(306, 306, 306)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbNgayTestPCR)
                                .addGap(181, 181, 181)
                                .addComponent(jdcNgayTestPCR, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbNgayTestNhanh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jdcNgayTestNhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbSoThangLaF0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfSoThangF0, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jlbNoiLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jtfNoiLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jlbNoiO, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jtfNoiO, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbMABN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jdcNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfMABN, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbPhuong_Xa)
                                    .addComponent(jlbSĐT))
                                .addGap(67, 67, 67)
                                .addComponent(jcobPhuong_Xa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jtfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jlbNgayXHTTDT)
                                .addGap(59, 59, 59)
                                .addComponent(jdcNgayXHTTDT, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 9, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbHoTen)
                    .addComponent(jtfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbMABN)
                    .addComponent(jtfMABN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlbGioiTinh)
                        .addComponent(jcbNam)
                        .addComponent(jcbNu)
                        .addComponent(jlbNgaySinh))
                    .addComponent(jdcNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbTinh_ThanhPho)
                            .addComponent(jcobTinh_ThanhPho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbNoiO)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jtfNoiO, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlbQuan_Huyen)
                                .addComponent(jcobQuan_Huyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jlbPhuong_Xa))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jcobPhuong_Xa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfNgheNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlbNgheNghiep)
                        .addComponent(jlbNoiLamViec))
                    .addComponent(jtfNoiLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbCMND_CCCD)
                            .addComponent(jtfCMND_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbSĐT)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jtfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbNgayTiepNhan)
                            .addComponent(jdcNgayTnF0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbNgayXHTTDT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jlbTungLaF0)
                                            .addComponent(jcbTungLaF0_Co)
                                            .addComponent(jcbTungLaF0_Khong)
                                            .addComponent(jlbSoThangLaF0)
                                            .addComponent(jtfSoThangF0, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jlbTestNhanh)
                                            .addComponent(jcbTestNhanh_Co)
                                            .addComponent(jcbTestNhanh_Khong)
                                            .addComponent(jlbNgayTestNhanh)
                                            .addComponent(jlbTestNhanh1)))
                                    .addComponent(jdcNgayTestNhanh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcobKQTestNhanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlbRT_PCR)
                                .addComponent(jcbTestPCR_Co)
                                .addComponent(jcbTestPCR_Khong)
                                .addComponent(jlbNgayTestPCR)
                                .addComponent(jlbTestNhanh2)
                                .addComponent(jcobKQTestPCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jdcNgayTestPCR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jdcNgayXHTTDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfHoTenActionPerformed

    private void jtfNgheNghiepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNgheNghiepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNgheNghiepActionPerformed

    private void jcobTinh_ThanhPhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcobTinh_ThanhPhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcobTinh_ThanhPhoActionPerformed

    private void jcobQuan_HuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcobQuan_HuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcobQuan_HuyenActionPerformed

    private void jtfCMND_CCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCMND_CCCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCMND_CCCDActionPerformed

    private void jcbTungLaF0_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTungLaF0_CoActionPerformed
        // TODO add your handling code here:
        jtfSoThangF0.setEnabled(true);
    }//GEN-LAST:event_jcbTungLaF0_CoActionPerformed

    private void jcbNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbNuActionPerformed

    private void jcbNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbNamActionPerformed

    private void jcbTungLaF0_KhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTungLaF0_KhongActionPerformed
        // TODO add your handling code here:
        jtfSoThangF0.setEnabled(false);
        
    }//GEN-LAST:event_jcbTungLaF0_KhongActionPerformed

    private void jcbTestNhanh_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTestNhanh_CoActionPerformed
        // TODO add your handling code here:
        jcobKQTestNhanh.setEnabled(true);
    }//GEN-LAST:event_jcbTestNhanh_CoActionPerformed

    private void jcbTestNhanh_KhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTestNhanh_KhongActionPerformed
        // TODO add your handling code here:
        jcobKQTestNhanh.setEnabled(false);
        jcobKQTestNhanh.setSelectedItem(null);
        
         jdcNgayTestNhanh.setEnabled(false);
        
         
//        jdcNgayTestNhanh.setDateFormatString("00-00-0000");
       
    }//GEN-LAST:event_jcbTestNhanh_KhongActionPerformed

    private void jcbTestPCR_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTestPCR_CoActionPerformed
        // TODO add your handling code here:
        jcobKQTestPCR.setEnabled(true);
    }//GEN-LAST:event_jcbTestPCR_CoActionPerformed

    private void jcbTestPCR_KhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTestPCR_KhongActionPerformed
        // TODO add your handling code here:
         jcobKQTestPCR.setEnabled(false);
        jcobKQTestPCR.setSelectedItem(null);
        jdcNgayTestPCR.setEnabled(false);
    }//GEN-LAST:event_jcbTestPCR_KhongActionPerformed

    private void jtfMABNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMABNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMABNActionPerformed

    private void jtfSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSDTActionPerformed

    private void jcobPhuong_XaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcobPhuong_XaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcobPhuong_XaActionPerformed

    private void jtfNoiOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNoiOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNoiOActionPerformed

    private void jtfNoiLamViecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNoiLamViecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNoiLamViecActionPerformed

    private void jtfSoThangF0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSoThangF0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSoThangF0ActionPerformed

    private void jcobKQTestNhanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcobKQTestNhanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcobKQTestNhanhActionPerformed

    private void jcobKQTestPCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcobKQTestPCRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcobKQTestPCRActionPerformed

    private void jcbTestNhanh_KhongStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jcbTestNhanh_KhongStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcbTestNhanh_KhongStateChanged

    private void jtfCMND_CCCDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCMND_CCCDKeyPressed
        // TODO add your handling code here:
        
        String sdt = jtfCMND_CCCD.getText();
        int length = sdt.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='0'&& evt.getKeyChar()<='9'){
            if(length<12){
                jtfCMND_CCCD.setEditable(true);
            }else{
                jtfCMND_CCCD.setEditable(false);
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                jtfCMND_CCCD.setEditable(true);
            }else{
                jtfCMND_CCCD.setEditable(false);
            }
        }
    }//GEN-LAST:event_jtfCMND_CCCDKeyPressed

    private void jtfSDTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSDTKeyPressed
        // TODO add your handling code here:
        String sdt = jtfSDT.getText();
        int length = sdt.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='0'&& evt.getKeyChar()<='9'){
            if(length<10){
                jtfSDT.setEditable(true);
            }else{
                jtfSDT.setEditable(false);
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                jtfSDT.setEditable(true);
            }else{
                jtfSDT.setEditable(false);
            }
        }
    }//GEN-LAST:event_jtfSDTKeyPressed

    public void MyinnitsetMBBN(){
       LayMABNTuDong td= new LayMABNTuDong();
        try {
            this.jtfMABN.setText(td.SetMABN());
            Color color=new Color(140,140,140);
            this.jtfMABN.setBackground(color);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TTCoBan_ThemBN.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TTCoBan_ThemBN.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnG_GioiTinh;
    private javax.swing.ButtonGroup btnG_RTPCR;
    private javax.swing.ButtonGroup btnG_TestNhanh;
    private javax.swing.ButtonGroup btnG_TunglaF0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jcbNam;
    private javax.swing.JCheckBox jcbNu;
    private javax.swing.JCheckBox jcbTestNhanh_Co;
    private javax.swing.JCheckBox jcbTestNhanh_Khong;
    private javax.swing.JCheckBox jcbTestPCR_Co;
    private javax.swing.JCheckBox jcbTestPCR_Khong;
    private javax.swing.JCheckBox jcbTungLaF0_Co;
    private javax.swing.JCheckBox jcbTungLaF0_Khong;
    private javax.swing.JComboBox<String> jcobKQTestNhanh;
    private javax.swing.JComboBox<String> jcobKQTestPCR;
    private javax.swing.JComboBox<String> jcobPhuong_Xa;
    private javax.swing.JComboBox<String> jcobQuan_Huyen;
    private javax.swing.JComboBox<String> jcobTinh_ThanhPho;
    private com.toedter.calendar.JDateChooser jdcNgaySinh;
    private com.toedter.calendar.JDateChooser jdcNgayTestNhanh;
    private com.toedter.calendar.JDateChooser jdcNgayTestPCR;
    private com.toedter.calendar.JDateChooser jdcNgayTnF0;
    private com.toedter.calendar.JDateChooser jdcNgayXHTTDT;
    private javax.swing.JLabel jlbCMND_CCCD;
    private javax.swing.JLabel jlbGioiTinh;
    private javax.swing.JLabel jlbHoTen;
    private javax.swing.JLabel jlbMABN;
    private javax.swing.JLabel jlbNgaySinh;
    private javax.swing.JLabel jlbNgayTestNhanh;
    private javax.swing.JLabel jlbNgayTestPCR;
    private javax.swing.JLabel jlbNgayTiepNhan;
    private javax.swing.JLabel jlbNgayXHTTDT;
    private javax.swing.JLabel jlbNgheNghiep;
    private javax.swing.JLabel jlbNoiLamViec;
    private javax.swing.JLabel jlbNoiO;
    private javax.swing.JLabel jlbPhuong_Xa;
    private javax.swing.JLabel jlbQuan_Huyen;
    private javax.swing.JLabel jlbRT_PCR;
    private javax.swing.JLabel jlbSoThangLaF0;
    private javax.swing.JLabel jlbSĐT;
    private javax.swing.JLabel jlbTestNhanh;
    private javax.swing.JLabel jlbTestNhanh1;
    private javax.swing.JLabel jlbTestNhanh2;
    private javax.swing.JLabel jlbTinh_ThanhPho;
    private javax.swing.JLabel jlbTungLaF0;
    private javax.swing.JTextField jtfCMND_CCCD;
    private javax.swing.JTextField jtfHoTen;
    private javax.swing.JTextField jtfMABN;
    private javax.swing.JTextField jtfNgheNghiep;
    private javax.swing.JTextField jtfNoiLamViec;
    private javax.swing.JTextField jtfNoiO;
    private javax.swing.JTextField jtfSDT;
    private javax.swing.JTextField jtfSoThangF0;
    // End of variables declaration//GEN-END:variables
    
}

