/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.da.qlf0.view.CapNhat;

/**
 *
 * @author Minh Cuong
 */
public class BenhNen_CapNhat extends javax.swing.JPanel {

    /**
     * Creates new form BenhNen_ThemBN
     */
    public BenhNen_CapNhat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnG_MangThai = new javax.swing.ButtonGroup();
        btnG_HauSan = new javax.swing.ButtonGroup();
        btnG_XNTreSS = new javax.swing.ButtonGroup();
        btnG_KQXN = new javax.swing.ButtonGroup();
        btnG_HuyetAp = new javax.swing.ButtonGroup();
        btnG_DTD = new javax.swing.ButtonGroup();
        btnG_TimMach = new javax.swing.ButtonGroup();
        btnG_MMNao = new javax.swing.ButtonGroup();
        btnG_ThanMT = new javax.swing.ButtonGroup();
        btnG_HenKQ = new javax.swing.ButtonGroup();
        btnG_BeoPhi = new javax.swing.ButtonGroup();
        btnG_THMD = new javax.swing.ButtonGroup();
        btnG_PhoiMT = new javax.swing.ButtonGroup();
        btnG_UngThu = new javax.swing.ButtonGroup();
        btn_GHIV = new javax.swing.ButtonGroup();
        btnG_BenhGan = new javax.swing.ButtonGroup();
        btnG_HCDown = new javax.swing.ButtonGroup();
        btn_GRLCGN = new javax.swing.ButtonGroup();
        btnG_Ghep = new javax.swing.ButtonGroup();
        btnG_CacLBHT = new javax.swing.ButtonGroup();
        btnG_TKMT = new javax.swing.ButtonGroup();
        btnG_Steroid = new javax.swing.ButtonGroup();
        btnG_ThuocMD = new javax.swing.ButtonGroup();
        btnG_ThuocCovid = new javax.swing.ButtonGroup();
        btnG_KhangSinh = new javax.swing.ButtonGroup();
        btnG_KhangVirus = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        jRadioButton33 = new javax.swing.JRadioButton();
        jRadioButton34 = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jRadioButton37 = new javax.swing.JRadioButton();
        jRadioButton38 = new javax.swing.JRadioButton();
        jRadioButton39 = new javax.swing.JRadioButton();
        jRadioButton40 = new javax.swing.JRadioButton();
        jRadioButton41 = new javax.swing.JRadioButton();
        jRadioButton42 = new javax.swing.JRadioButton();
        jLabel33 = new javax.swing.JLabel();
        jRadioButton43 = new javax.swing.JRadioButton();
        jRadioButton44 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jRadioButton45 = new javax.swing.JRadioButton();
        jRadioButton46 = new javax.swing.JRadioButton();
        jRadioButton47 = new javax.swing.JRadioButton();
        jRadioButton48 = new javax.swing.JRadioButton();
        jRadioButton49 = new javax.swing.JRadioButton();
        jRadioButton50 = new javax.swing.JRadioButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jRadioButton51 = new javax.swing.JRadioButton();
        jRadioButton52 = new javax.swing.JRadioButton();
        jRadioButton53 = new javax.swing.JRadioButton();
        jRadioButton54 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(20, 20, 20));
        jLabel1.setText("TIỀN SỬ BỆNH NỀN");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(526, 526, 526)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 41, 102));
        jLabel8.setText("BỆNH NỀN");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(20, 20, 20));
        jLabel12.setText("Mang thai:");

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MangThai.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton2.setText("Có");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(166, 166, 166));

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MangThai.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("Không");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(20, 20, 20));
        jLabel13.setText("Nếu Có: Đánh giá số tuần mang thai");

        jTextField1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(20, 20, 20));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(20, 20, 20));
        jLabel14.setText("Hậu sản ( trong vòng 6 tuần ):");

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        btnG_HauSan.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton4.setText("Có");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        btnG_HauSan.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton5.setSelected(true);
        jRadioButton5.setText("Không");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(20, 20, 20));
        jLabel15.setText("Trẻ sơ sinh được xét nghiệm Covid-19");

        jRadioButton6.setBackground(new java.awt.Color(255, 255, 255));
        btnG_XNTreSS.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton6.setText("Có");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jRadioButton7.setBackground(new java.awt.Color(255, 255, 255));
        btnG_XNTreSS.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton7.setText("Không");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(20, 20, 20));
        jLabel16.setText("Nếu Có: Kết quả xét nghiệm là :");

        jRadioButton8.setBackground(new java.awt.Color(255, 255, 255));
        btnG_KQXN.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton8.setText("Âm tính");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        jRadioButton9.setBackground(new java.awt.Color(255, 255, 255));
        btnG_KQXN.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton9.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton9.setText("Dương tính");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        jRadioButton10.setBackground(new java.awt.Color(255, 255, 255));
        btnG_KQXN.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton10.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton10.setText("Chưa có kết quả");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 41, 102));
        jLabel9.setText("MANG THAI");

        jSeparator4.setBackground(new java.awt.Color(166, 166, 166));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(20, 20, 20));
        jLabel17.setText("Tăng huyết áp:");

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(20, 20, 20));
        jLabel18.setText("Đái tháo đường:");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(20, 20, 20));
        jLabel19.setText("Bệnh tim mạch (suy tim, động mạch vành hay cơ tim):");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(20, 20, 20));
        jLabel20.setText("Bệnh lý mạch máu não:");

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(20, 20, 20));
        jLabel21.setText("Bệnh thận mãn tính:");

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(20, 20, 20));
        jLabel22.setText("Hen khí quản ( chẩn đón bởi bác sĩ ):");

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(20, 20, 20));
        jLabel23.setText("Béo phì ( xác nhận bởi nhân viên y tế ):");

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(20, 20, 20));
        jLabel24.setText("Thiếu hụt miễn dịch:");

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(20, 20, 20));
        jLabel25.setText("Bệnh phổi mãn tính ( không phải hen suyễn ):");

        jRadioButton11.setBackground(new java.awt.Color(255, 255, 255));
        btnG_HuyetAp.add(jRadioButton11);
        jRadioButton11.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton11.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton11.setText("Có");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });

        jRadioButton12.setBackground(new java.awt.Color(255, 255, 255));
        btnG_HuyetAp.add(jRadioButton12);
        jRadioButton12.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton12.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton12.setSelected(true);
        jRadioButton12.setText("Không");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });

        jRadioButton13.setBackground(new java.awt.Color(255, 255, 255));
        btnG_TimMach.add(jRadioButton13);
        jRadioButton13.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton13.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton13.setText("Có");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });

        jRadioButton14.setBackground(new java.awt.Color(255, 255, 255));
        btnG_TimMach.add(jRadioButton14);
        jRadioButton14.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton14.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton14.setSelected(true);
        jRadioButton14.setText("Không");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });

        jRadioButton15.setBackground(new java.awt.Color(255, 255, 255));
        btnG_DTD.add(jRadioButton15);
        jRadioButton15.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton15.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton15.setText("Có");
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });

        jRadioButton16.setBackground(new java.awt.Color(255, 255, 255));
        btnG_DTD.add(jRadioButton16);
        jRadioButton16.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton16.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton16.setSelected(true);
        jRadioButton16.setText("Không");
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton16ActionPerformed(evt);
            }
        });

        jRadioButton17.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MMNao.add(jRadioButton17);
        jRadioButton17.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton17.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton17.setText("Có");
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton17ActionPerformed(evt);
            }
        });

        jRadioButton18.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MMNao.add(jRadioButton18);
        jRadioButton18.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton18.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton18.setSelected(true);
        jRadioButton18.setText("Không");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });

        jRadioButton19.setBackground(new java.awt.Color(255, 255, 255));
        btnG_ThanMT.add(jRadioButton19);
        jRadioButton19.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton19.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton19.setText("Có");
        jRadioButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton19ActionPerformed(evt);
            }
        });

        jRadioButton20.setBackground(new java.awt.Color(255, 255, 255));
        btnG_ThanMT.add(jRadioButton20);
        jRadioButton20.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton20.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton20.setSelected(true);
        jRadioButton20.setText("Không");
        jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton20ActionPerformed(evt);
            }
        });

        jRadioButton21.setBackground(new java.awt.Color(255, 255, 255));
        btnG_HenKQ.add(jRadioButton21);
        jRadioButton21.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton21.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton21.setText("Có");
        jRadioButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton21ActionPerformed(evt);
            }
        });

        jRadioButton22.setBackground(new java.awt.Color(255, 255, 255));
        btnG_HenKQ.add(jRadioButton22);
        jRadioButton22.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton22.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton22.setSelected(true);
        jRadioButton22.setText("Không");
        jRadioButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton22ActionPerformed(evt);
            }
        });

        jRadioButton23.setBackground(new java.awt.Color(255, 255, 255));
        btnG_BeoPhi.add(jRadioButton23);
        jRadioButton23.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton23.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton23.setText("Có");
        jRadioButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton23ActionPerformed(evt);
            }
        });

        jRadioButton24.setBackground(new java.awt.Color(255, 255, 255));
        btnG_BeoPhi.add(jRadioButton24);
        jRadioButton24.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton24.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton24.setSelected(true);
        jRadioButton24.setText("Không");
        jRadioButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton24ActionPerformed(evt);
            }
        });

        jRadioButton25.setBackground(new java.awt.Color(255, 255, 255));
        btnG_THMD.add(jRadioButton25);
        jRadioButton25.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton25.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton25.setText("Có");
        jRadioButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton25ActionPerformed(evt);
            }
        });

        jRadioButton26.setBackground(new java.awt.Color(255, 255, 255));
        btnG_THMD.add(jRadioButton26);
        jRadioButton26.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton26.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton26.setSelected(true);
        jRadioButton26.setText("Không");
        jRadioButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton26ActionPerformed(evt);
            }
        });

        jRadioButton27.setBackground(new java.awt.Color(255, 255, 255));
        btnG_PhoiMT.add(jRadioButton27);
        jRadioButton27.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton27.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton27.setText("Có");
        jRadioButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton27ActionPerformed(evt);
            }
        });

        jRadioButton28.setBackground(new java.awt.Color(255, 255, 255));
        btnG_PhoiMT.add(jRadioButton28);
        jRadioButton28.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton28.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton28.setSelected(true);
        jRadioButton28.setText("Không");
        jRadioButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton28ActionPerformed(evt);
            }
        });

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(20, 20, 20));
        jLabel26.setText("Ung thư:");

        jRadioButton29.setBackground(new java.awt.Color(255, 255, 255));
        btnG_UngThu.add(jRadioButton29);
        jRadioButton29.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton29.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton29.setText("Có");
        jRadioButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton29ActionPerformed(evt);
            }
        });

        jRadioButton30.setBackground(new java.awt.Color(255, 255, 255));
        btnG_UngThu.add(jRadioButton30);
        jRadioButton30.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton30.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton30.setSelected(true);
        jRadioButton30.setText("Không");
        jRadioButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton30ActionPerformed(evt);
            }
        });

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(20, 20, 20));
        jLabel27.setText("AIDS/HIV:");

        jRadioButton31.setBackground(new java.awt.Color(255, 255, 255));
        btn_GHIV.add(jRadioButton31);
        jRadioButton31.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton31.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton31.setText("Có");
        jRadioButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton31ActionPerformed(evt);
            }
        });

        jRadioButton32.setBackground(new java.awt.Color(255, 255, 255));
        btn_GHIV.add(jRadioButton32);
        jRadioButton32.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton32.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton32.setSelected(true);
        jRadioButton32.setText("Không");
        jRadioButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton32ActionPerformed(evt);
            }
        });

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(20, 20, 20));
        jLabel28.setText("Bệnh gan:");

        jRadioButton33.setBackground(new java.awt.Color(255, 255, 255));
        btnG_BenhGan.add(jRadioButton33);
        jRadioButton33.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton33.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton33.setText("Có");
        jRadioButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton33ActionPerformed(evt);
            }
        });

        jRadioButton34.setBackground(new java.awt.Color(255, 255, 255));
        btnG_BenhGan.add(jRadioButton34);
        jRadioButton34.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton34.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton34.setSelected(true);
        jRadioButton34.setText("Không");
        jRadioButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton34ActionPerformed(evt);
            }
        });

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(20, 20, 20));
        jLabel29.setText("Hội chứng down:");

        jRadioButton35.setBackground(new java.awt.Color(255, 255, 255));
        btnG_HCDown.add(jRadioButton35);
        jRadioButton35.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton35.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton35.setText("Có");
        jRadioButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton35ActionPerformed(evt);
            }
        });

        jRadioButton36.setBackground(new java.awt.Color(255, 255, 255));
        btnG_HCDown.add(jRadioButton36);
        jRadioButton36.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton36.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton36.setSelected(true);
        jRadioButton36.setText("Không");
        jRadioButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton36ActionPerformed(evt);
            }
        });

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(20, 20, 20));
        jLabel30.setText("Rối loạn sử dụng chất gây nghiện:");

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(20, 20, 20));
        jLabel31.setText("Ghép tạng hoặc cấy ghép tế bào gốc tạo máu:");

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(20, 20, 20));
        jLabel32.setText("Các loại bệnh hệ thống:");

        jRadioButton37.setBackground(new java.awt.Color(255, 255, 255));
        btn_GRLCGN.add(jRadioButton37);
        jRadioButton37.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton37.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton37.setText("Có");
        jRadioButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton37ActionPerformed(evt);
            }
        });

        jRadioButton38.setBackground(new java.awt.Color(255, 255, 255));
        btn_GRLCGN.add(jRadioButton38);
        jRadioButton38.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton38.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton38.setSelected(true);
        jRadioButton38.setText("Không");
        jRadioButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton38ActionPerformed(evt);
            }
        });

        jRadioButton39.setBackground(new java.awt.Color(255, 255, 255));
        btnG_Ghep.add(jRadioButton39);
        jRadioButton39.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton39.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton39.setText("Có");
        jRadioButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton39ActionPerformed(evt);
            }
        });

        jRadioButton40.setBackground(new java.awt.Color(255, 255, 255));
        btnG_Ghep.add(jRadioButton40);
        jRadioButton40.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton40.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton40.setSelected(true);
        jRadioButton40.setText("Không");
        jRadioButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton40ActionPerformed(evt);
            }
        });

        jRadioButton41.setBackground(new java.awt.Color(255, 255, 255));
        btnG_CacLBHT.add(jRadioButton41);
        jRadioButton41.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton41.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton41.setText("Có");
        jRadioButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton41ActionPerformed(evt);
            }
        });

        jRadioButton42.setBackground(new java.awt.Color(255, 255, 255));
        btnG_CacLBHT.add(jRadioButton42);
        jRadioButton42.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton42.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton42.setSelected(true);
        jRadioButton42.setText("Không");
        jRadioButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton42ActionPerformed(evt);
            }
        });

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(20, 20, 20));
        jLabel33.setText("Bệnh thần kinh mãn tính ( bao gồm sa sút trí tuệ ):");

        jRadioButton43.setBackground(new java.awt.Color(255, 255, 255));
        btnG_TKMT.add(jRadioButton43);
        jRadioButton43.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton43.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton43.setText("Có");
        jRadioButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton43ActionPerformed(evt);
            }
        });

        jRadioButton44.setBackground(new java.awt.Color(255, 255, 255));
        btnG_TKMT.add(jRadioButton44);
        jRadioButton44.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton44.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton44.setSelected(true);
        jRadioButton44.setText("Không");
        jRadioButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton44ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 41, 102));
        jLabel10.setText("CÁC LOẠI THUỐC ĐÃ SỬ DỤNG");

        jSeparator5.setBackground(new java.awt.Color(166, 166, 166));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(20, 20, 20));
        jLabel34.setText("Steroid:");

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(20, 20, 20));
        jLabel35.setText("Các thuốc ứng chế miễn dịch khác:");

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(20, 20, 20));
        jLabel36.setText("Các loại thuốc điều trị Covid:");

        jRadioButton45.setBackground(new java.awt.Color(255, 255, 255));
        btnG_Steroid.add(jRadioButton45);
        jRadioButton45.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton45.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton45.setText("Có");
        jRadioButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton45ActionPerformed(evt);
            }
        });

        jRadioButton46.setBackground(new java.awt.Color(255, 255, 255));
        btnG_Steroid.add(jRadioButton46);
        jRadioButton46.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton46.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton46.setSelected(true);
        jRadioButton46.setText("Không");
        jRadioButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton46ActionPerformed(evt);
            }
        });

        jRadioButton47.setBackground(new java.awt.Color(255, 255, 255));
        btnG_ThuocMD.add(jRadioButton47);
        jRadioButton47.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton47.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton47.setText("Có");
        jRadioButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton47ActionPerformed(evt);
            }
        });

        jRadioButton48.setBackground(new java.awt.Color(255, 255, 255));
        btnG_ThuocMD.add(jRadioButton48);
        jRadioButton48.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton48.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton48.setSelected(true);
        jRadioButton48.setText("Không");
        jRadioButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton48ActionPerformed(evt);
            }
        });

        jRadioButton49.setBackground(new java.awt.Color(255, 255, 255));
        btnG_ThuocCovid.add(jRadioButton49);
        jRadioButton49.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton49.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton49.setText("Có");
        jRadioButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton49ActionPerformed(evt);
            }
        });

        jRadioButton50.setBackground(new java.awt.Color(255, 255, 255));
        btnG_ThuocCovid.add(jRadioButton50);
        jRadioButton50.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton50.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton50.setSelected(true);
        jRadioButton50.setText("Không");
        jRadioButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton50ActionPerformed(evt);
            }
        });

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(20, 20, 20));
        jLabel37.setText("Kháng sinh:");

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(20, 20, 20));
        jLabel38.setText("Kháng virus:");

        jRadioButton51.setBackground(new java.awt.Color(255, 255, 255));
        btnG_KhangSinh.add(jRadioButton51);
        jRadioButton51.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton51.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton51.setText("Có");
        jRadioButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton51ActionPerformed(evt);
            }
        });

        jRadioButton52.setBackground(new java.awt.Color(255, 255, 255));
        btnG_KhangSinh.add(jRadioButton52);
        jRadioButton52.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton52.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton52.setSelected(true);
        jRadioButton52.setText("Không");
        jRadioButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton52ActionPerformed(evt);
            }
        });

        jRadioButton53.setBackground(new java.awt.Color(255, 255, 255));
        btnG_KhangVirus.add(jRadioButton53);
        jRadioButton53.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton53.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton53.setText("Có");
        jRadioButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton53ActionPerformed(evt);
            }
        });

        jRadioButton54.setBackground(new java.awt.Color(255, 255, 255));
        btnG_KhangVirus.add(jRadioButton54);
        jRadioButton54.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jRadioButton54.setForeground(new java.awt.Color(20, 20, 20));
        jRadioButton54.setSelected(true);
        jRadioButton54.setText("Không");
        jRadioButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton54ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 1766, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1766, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addGap(180, 180, 180)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton4))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton5)
                                    .addComponent(jRadioButton3))
                                .addGap(160, 160, 160)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel16))
                                .addGap(134, 134, 134)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton6)
                                                .addGap(50, 50, 50)
                                                .addComponent(jRadioButton7))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton9)
                                                .addGap(39, 39, 39)
                                                .addComponent(jRadioButton8)))
                                        .addGap(39, 39, 39)
                                        .addComponent(jRadioButton10))
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel18))
                                        .addGap(273, 273, 273)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton15)
                                            .addComponent(jRadioButton11)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton17)
                                            .addComponent(jRadioButton13)
                                            .addComponent(jRadioButton19)
                                            .addComponent(jRadioButton21)
                                            .addComponent(jRadioButton23)
                                            .addComponent(jRadioButton25)
                                            .addComponent(jRadioButton27)))
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton28)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton12)
                                            .addComponent(jRadioButton16)
                                            .addComponent(jRadioButton14)
                                            .addComponent(jRadioButton18)
                                            .addComponent(jRadioButton20)
                                            .addComponent(jRadioButton22)
                                            .addComponent(jRadioButton24)
                                            .addComponent(jRadioButton26))
                                        .addGap(165, 165, 165)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel26)
                                                    .addComponent(jLabel27)
                                                    .addComponent(jLabel28)
                                                    .addComponent(jLabel29)
                                                    .addComponent(jLabel30)
                                                    .addComponent(jLabel31)
                                                    .addComponent(jLabel32))
                                                .addGap(42, 42, 42)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRadioButton29)
                                                    .addComponent(jRadioButton31)
                                                    .addComponent(jRadioButton33)
                                                    .addComponent(jRadioButton35)
                                                    .addComponent(jRadioButton37)
                                                    .addComponent(jRadioButton39)
                                                    .addComponent(jRadioButton41)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel33)
                                                .addGap(15, 15, 15)
                                                .addComponent(jRadioButton43)))
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton44)
                                            .addComponent(jRadioButton42)
                                            .addComponent(jRadioButton40)
                                            .addComponent(jRadioButton38)
                                            .addComponent(jRadioButton36)
                                            .addComponent(jRadioButton34)
                                            .addComponent(jRadioButton32)
                                            .addComponent(jRadioButton30)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 1766, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel36))
                                .addGap(139, 139, 139)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton45)
                                    .addComponent(jRadioButton47)
                                    .addComponent(jRadioButton49))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton50)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton46)
                                            .addComponent(jRadioButton48))
                                        .addGap(165, 165, 165)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel37)
                                            .addComponent(jLabel38))
                                        .addGap(272, 272, 272)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton51)
                                            .addComponent(jRadioButton53))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton54)
                                            .addComponent(jRadioButton52))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel9)
                    .addContainerGap(1638, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jLabel13)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jLabel15)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton10))
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton12)
                    .addComponent(jLabel26)
                    .addComponent(jRadioButton29)
                    .addComponent(jRadioButton30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jRadioButton15)
                    .addComponent(jRadioButton16)
                    .addComponent(jLabel27)
                    .addComponent(jRadioButton31)
                    .addComponent(jRadioButton32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jRadioButton13)
                    .addComponent(jRadioButton14)
                    .addComponent(jLabel28)
                    .addComponent(jRadioButton33)
                    .addComponent(jRadioButton34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jRadioButton17)
                    .addComponent(jRadioButton18)
                    .addComponent(jLabel29)
                    .addComponent(jRadioButton35)
                    .addComponent(jRadioButton36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jRadioButton19)
                    .addComponent(jRadioButton20)
                    .addComponent(jLabel30)
                    .addComponent(jRadioButton37)
                    .addComponent(jRadioButton38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jRadioButton21)
                    .addComponent(jRadioButton22)
                    .addComponent(jLabel31)
                    .addComponent(jRadioButton39)
                    .addComponent(jRadioButton40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jRadioButton23)
                    .addComponent(jRadioButton24)
                    .addComponent(jLabel32)
                    .addComponent(jRadioButton41)
                    .addComponent(jRadioButton42))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jRadioButton25)
                    .addComponent(jRadioButton26)
                    .addComponent(jLabel33)
                    .addComponent(jRadioButton43)
                    .addComponent(jRadioButton44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jRadioButton27)
                    .addComponent(jRadioButton28))
                .addGap(33, 33, 33)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jRadioButton45)
                    .addComponent(jRadioButton46)
                    .addComponent(jLabel37)
                    .addComponent(jRadioButton51)
                    .addComponent(jRadioButton52))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jRadioButton47)
                    .addComponent(jRadioButton48)
                    .addComponent(jLabel38)
                    .addComponent(jRadioButton53)
                    .addComponent(jRadioButton54))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jRadioButton49)
                    .addComponent(jRadioButton50))
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addComponent(jLabel9)
                    .addContainerGap(610, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    private void jRadioButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton16ActionPerformed

    private void jRadioButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton17ActionPerformed

    private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton18ActionPerformed

    private void jRadioButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton19ActionPerformed

    private void jRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton20ActionPerformed

    private void jRadioButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton21ActionPerformed

    private void jRadioButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton22ActionPerformed

    private void jRadioButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton23ActionPerformed

    private void jRadioButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton24ActionPerformed

    private void jRadioButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton25ActionPerformed

    private void jRadioButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton26ActionPerformed

    private void jRadioButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton27ActionPerformed

    private void jRadioButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton28ActionPerformed

    private void jRadioButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton29ActionPerformed

    private void jRadioButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton30ActionPerformed

    private void jRadioButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton31ActionPerformed

    private void jRadioButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton32ActionPerformed

    private void jRadioButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton33ActionPerformed

    private void jRadioButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton34ActionPerformed

    private void jRadioButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton35ActionPerformed

    private void jRadioButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton36ActionPerformed

    private void jRadioButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton37ActionPerformed

    private void jRadioButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton38ActionPerformed

    private void jRadioButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton39ActionPerformed

    private void jRadioButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton40ActionPerformed

    private void jRadioButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton41ActionPerformed

    private void jRadioButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton42ActionPerformed

    private void jRadioButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton43ActionPerformed

    private void jRadioButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton44ActionPerformed

    private void jRadioButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton45ActionPerformed

    private void jRadioButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton46ActionPerformed

    private void jRadioButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton47ActionPerformed

    private void jRadioButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton48ActionPerformed

    private void jRadioButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton49ActionPerformed

    private void jRadioButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton50ActionPerformed

    private void jRadioButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton51ActionPerformed

    private void jRadioButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton52ActionPerformed

    private void jRadioButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton53ActionPerformed

    private void jRadioButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton54ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnG_BenhGan;
    private javax.swing.ButtonGroup btnG_BeoPhi;
    private javax.swing.ButtonGroup btnG_CacLBHT;
    private javax.swing.ButtonGroup btnG_DTD;
    private javax.swing.ButtonGroup btnG_Ghep;
    private javax.swing.ButtonGroup btnG_HCDown;
    private javax.swing.ButtonGroup btnG_HauSan;
    private javax.swing.ButtonGroup btnG_HenKQ;
    private javax.swing.ButtonGroup btnG_HuyetAp;
    private javax.swing.ButtonGroup btnG_KQXN;
    private javax.swing.ButtonGroup btnG_KhangSinh;
    private javax.swing.ButtonGroup btnG_KhangVirus;
    private javax.swing.ButtonGroup btnG_MMNao;
    private javax.swing.ButtonGroup btnG_MangThai;
    private javax.swing.ButtonGroup btnG_PhoiMT;
    private javax.swing.ButtonGroup btnG_Steroid;
    private javax.swing.ButtonGroup btnG_THMD;
    private javax.swing.ButtonGroup btnG_TKMT;
    private javax.swing.ButtonGroup btnG_ThanMT;
    private javax.swing.ButtonGroup btnG_ThuocCovid;
    private javax.swing.ButtonGroup btnG_ThuocMD;
    private javax.swing.ButtonGroup btnG_TimMach;
    private javax.swing.ButtonGroup btnG_UngThu;
    private javax.swing.ButtonGroup btnG_XNTreSS;
    private javax.swing.ButtonGroup btn_GHIV;
    private javax.swing.ButtonGroup btn_GRLCGN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JRadioButton jRadioButton37;
    private javax.swing.JRadioButton jRadioButton38;
    private javax.swing.JRadioButton jRadioButton39;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton40;
    private javax.swing.JRadioButton jRadioButton41;
    private javax.swing.JRadioButton jRadioButton42;
    private javax.swing.JRadioButton jRadioButton43;
    private javax.swing.JRadioButton jRadioButton44;
    private javax.swing.JRadioButton jRadioButton45;
    private javax.swing.JRadioButton jRadioButton46;
    private javax.swing.JRadioButton jRadioButton47;
    private javax.swing.JRadioButton jRadioButton48;
    private javax.swing.JRadioButton jRadioButton49;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton50;
    private javax.swing.JRadioButton jRadioButton51;
    private javax.swing.JRadioButton jRadioButton52;
    private javax.swing.JRadioButton jRadioButton53;
    private javax.swing.JRadioButton jRadioButton54;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
