/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.da.qlf0.view.CapNhat;

import com.da.qlf0.bean.DanhMucCapNhatBN;
import com.da.qlf0.controller.ChuyenMH_CapNhat;
import com.da.qlf0.controller.XemTT_CapNhatDTController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author NDAT_UIT
 */
public class CapNhat_Frame extends javax.swing.JFrame {

    /**
     * Creates new form CapNhat_Frame
     */
    private TTCoBan_CapNhat node1 = new TTCoBan_CapNhat();
    private TiemVX_CapNhat node2 = new TiemVX_CapNhat();
    private BenhNen_CapNhat node3 = new BenhNen_CapNhat();
    private TinhTrangTT_CapNhat node4 = new TinhTrangTT_CapNhat();
    private QTDieuTri_CapNhat node5 = new QTDieuTri_CapNhat();
    private String MABN;
    public CapNhat_Frame(String MABN) {
        initComponents();
        ChuyenMH_CapNhat controller = new ChuyenMH_CapNhat(jpnView, node1, node2, node3, node4, node5);
        controller.setView(jpnTTCoBan, jlbTTCoBan);

        ArrayList<DanhMucCapNhatBN> listItem = new ArrayList<>();
        listItem.add(new DanhMucCapNhatBN("ThongTinCoBan", jpnTTCoBan, jlbTTCoBan));
        listItem.add(new DanhMucCapNhatBN("TiemVX", jpnTiemVX, jlbTiemVX));
        listItem.add(new DanhMucCapNhatBN("BenhNen", jpnBenhNen, jlbBenhNen));
        listItem.add(new DanhMucCapNhatBN("TinhTrang", jpnTinhTrang, jlbTinhTrang));
        listItem.add(new DanhMucCapNhatBN("QuaTrinhDieuTri", jpnQTDieuTri, jlbQTDieuTri));

        controller.setEvent(listItem);
        this.MABN=MABN;
    }

    public TTCoBan_CapNhat getNode1() {
        return node1;
    }

    public TiemVX_CapNhat getNode2() {
        return node2;
    }

    public BenhNen_CapNhat getNode3() {
        return node3;
    }

    public TinhTrangTT_CapNhat getNode4() {
        return node4;
    }

    public QTDieuTri_CapNhat getNode5() {
        return node5;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jpnTTCoBan = new javax.swing.JPanel();
        jlbTTCoBan = new javax.swing.JLabel();
        jpnTinhTrang = new javax.swing.JPanel();
        jlbTinhTrang = new javax.swing.JLabel();
        jpnTiemVX = new javax.swing.JPanel();
        jlbTiemVX = new javax.swing.JLabel();
        jpnBenhNen = new javax.swing.JPanel();
        jlbBenhNen = new javax.swing.JLabel();
        jpnQTDieuTri = new javax.swing.JPanel();
        jlbQTDieuTri = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(204, 102, 0));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cập nhật quá trình điều trị");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 115, 153));
        jLabel1.setText("<<BACK");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jpnTTCoBan.setBackground(new java.awt.Color(0, 180, 153));

        jlbTTCoBan.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jlbTTCoBan.setText("Thông tin cơ bản");

        javax.swing.GroupLayout jpnTTCoBanLayout = new javax.swing.GroupLayout(jpnTTCoBan);
        jpnTTCoBan.setLayout(jpnTTCoBanLayout);
        jpnTTCoBanLayout.setHorizontalGroup(
            jpnTTCoBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTTCoBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTTCoBan)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jpnTTCoBanLayout.setVerticalGroup(
            jpnTTCoBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTTCoBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTTCoBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnTinhTrang.setBackground(new java.awt.Color(0, 180, 153));

        jlbTinhTrang.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jlbTinhTrang.setText("Tình Trạng Lúc Tiếp Nhận");

        javax.swing.GroupLayout jpnTinhTrangLayout = new javax.swing.GroupLayout(jpnTinhTrang);
        jpnTinhTrang.setLayout(jpnTinhTrangLayout);
        jpnTinhTrangLayout.setHorizontalGroup(
            jpnTinhTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTinhTrangLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jlbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnTinhTrangLayout.setVerticalGroup(
            jpnTinhTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTinhTrangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTinhTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnTiemVX.setBackground(new java.awt.Color(0, 180, 153));

        jlbTiemVX.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jlbTiemVX.setText("Tiêm Vắc xin");

        jpnBenhNen.setBackground(new java.awt.Color(0, 180, 153));

        jlbBenhNen.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jlbBenhNen.setText("Bệnh Nền");

        javax.swing.GroupLayout jpnBenhNenLayout = new javax.swing.GroupLayout(jpnBenhNen);
        jpnBenhNen.setLayout(jpnBenhNenLayout);
        jpnBenhNenLayout.setHorizontalGroup(
            jpnBenhNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBenhNenLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlbBenhNen, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnBenhNenLayout.setVerticalGroup(
            jpnBenhNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBenhNenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbBenhNen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnTiemVXLayout = new javax.swing.GroupLayout(jpnTiemVX);
        jpnTiemVX.setLayout(jpnTiemVXLayout);
        jpnTiemVXLayout.setHorizontalGroup(
            jpnTiemVXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTiemVXLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jlbTiemVX, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnBenhNen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jpnTiemVXLayout.setVerticalGroup(
            jpnTiemVXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTiemVXLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTiemVX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpnTiemVXLayout.createSequentialGroup()
                .addComponent(jpnBenhNen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpnQTDieuTri.setBackground(new java.awt.Color(0, 180, 153));

        jlbQTDieuTri.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jlbQTDieuTri.setText("Quá Trình Điều Trị Tại Nhà");

        javax.swing.GroupLayout jpnQTDieuTriLayout = new javax.swing.GroupLayout(jpnQTDieuTri);
        jpnQTDieuTri.setLayout(jpnQTDieuTriLayout);
        jpnQTDieuTriLayout.setHorizontalGroup(
            jpnQTDieuTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQTDieuTriLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbQTDieuTri, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnQTDieuTriLayout.setVerticalGroup(
            jpnQTDieuTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQTDieuTriLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jlbQTDieuTri)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnTTCoBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnTiemVX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnQTDieuTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnTiemVX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnTTCoBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnTinhTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnQTDieuTri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnView.setPreferredSize(new java.awt.Dimension(0, 619));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1011, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame frame = new JFrame();
        String[] options = new String[2];
        options[0] = "Có";
        options[1] = "Không";
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showOptionDialog(frame.getContentPane(), "Xác nhận lưu thông tin?", "Lưu cập nhật", 0, JOptionPane.INFORMATION_MESSAGE, null, options, dialogButton);
        if(dialogResult == 0) {
            
                XemTT_CapNhatDTController tt_cn = new XemTT_CapNhatDTController(
                 this.node1.getJlbMABN().getText(),
                 this.node1.getJcbNam(),
                 this.node1.getJcbNu(),
                 this.node1.getJcbTestPCR_Co(),
                 this.node1.getJcbTestPCR_Khong(),
                 this.node1.getJcbTestNhanh_Co(),
                 this.node1.getJcbTestNhanh_Khong(),
                 this.node1.getJcbTungLaF0_Co(),
                 this.node1.getJcbTungLaF0_Khong(),
                 this.node1.getJcobPhuong_Xa(),
                 this.node1.getJcobQuan_Huyen(),
                 this.node1.getJcobTinh_ThanhPho(),
                 this.node1.getJdcNgaySinh(),
                 this.node1.getJdcNgayTnF0(),
                 this.node1.getJdcNgayTestNhanh(),
                 this.node1.getJdcNgayTestPCR(),
                 this.node1.getJcobKQTestNhanh(),
                 this.node1.getJcobKQTestPCR(),
                 this.node1.getJdcNgayXHTTDT(),
                 this.node1.getJtfCMND_CCCD(),
                 this.node1.getJtfHoTen(),
                 this.node1.getJtfMABN(),
                 this.node1.getJtfNgheNghiep(),
                 this.node1.getJtfNoiLamViec(),
                 this.node1.getJtfNoiO(),
                 this.node1.getJtfSDT(),
                 this.node1.getJtfSoThangF0(),
                
                
                
                 this.node2.getJcobTiemVX_1(),
                 this.node2.getJcobTiemVX_2(),
                 this.node2.getJcobTiemVX_3(),
                 this.node2.getJdcTGMui1(),
                 this.node2.getJdcTGMui2(),
                 this.node2.getJdcTGMui3(),
                 this.node2.getJrbChuaTiem(),
                 this.node2.getJrbTiem1Mui(),
                 this.node2.getJrbTiem2Mui(),
                 this.node2.getJrbTiem3Mui(),
                 this.node2.getJrbTiem_KhongBiet(),
        
                 this.node3.getJrbBenhGan_Co(),
                 this.node3.getJrbBenhGan_Khong(),
                 this.node3.getJrbBenhPhoiMT_Co(),
                 this.node3.getJrbBenhPhoiMT_Khong(),
                 this.node3.getJrbBenhTKMT_Co(),
                 this.node3.getJrbBenhTKMT_Khong(),
                 this.node3.getJrbBenhThanMT_Co(),
                 this.node3.getJrbBenhThanMT_Khong(),
                 this.node3.getJrbBenhTim_Co(),
                 this.node3.getJrbBenhTim_Khong(),
                 this.node3.getJrbBeoPhi_Co(),
                 this.node3.getJrbBeoPhi_Khong(),
                 this.node3.getJrbCLBenhHT_Co(),
                 this.node3.getJrbCLBenhHT_Khong(),
                 this.node3.getJrbDaiTD_Co(),
                 this.node3.getJrbDaiTD_Khong(),
                 this.node3.getJrbGhepTang_TBM_Co(),
                 this.node3.getJrbGhepTang_TBM_Khong(),
                 this.node3.getJrbHIV_Co(),
                 this.node3.getJrbHIV_Khong(),
                 this.node3.getJrbHauSan_Co(),
                 this.node3.getJrbHauSan_Khong(),
                 this.node3.getJrbHenKQ_Co(),
                 this.node3.getJrbHenKQ_Khong(),
                 this.node3.getJrbHoiChungDown_Co(),
                 this.node3.getJrbHoiChungDown_Khong(),
                 this.node3.getJrbKQXN_AT(),
                 this.node3.getJrbKQXN_ChuaCoKQ(),
                 this.node3.getJrbKQXN_DT(),
                 this.node3.getJrbKhangSinh_Co(),
                 this.node3.getJrbKhangSinh_Khong(),
                 this.node3.getJrbKhangVirus_Co(),
                 this.node3.getJrbKhangVirus_Khong(),
                 this.node3.getJrbMachMauNao_Co(),
                 this.node3.getJrbMachMauNao_Khong(),
                 this.node3.getJrbMangThai_Co(),
                 this.node3.getJrbMangThai_Khong(),
                 this.node3.getJrbRoiLoanSDCGN_Co(),
                 this.node3.getJrbRoiLoanSDCGN_Khong(),
                 this.node3.getJrbSteroid_Co(),
                 this.node3.getJrbSteroid_Khong(),
                 this.node3.getJrbTangHA_Co(),
                 this.node3.getJrbTangHA_Khong(),
                 this.node3.getJrbThieuMD_Co(),
                 this.node3.getJrbThieuMD_Khong(),
                 this.node3.getJrbThuocDTCovid_Co(),
                 this.node3.getJrbThuocDTCovid_Khong(),
                 this.node3.getJrbThuocMD_Co(),
                 this.node3.getJrbThuocMD_Khong(),
                 this.node3.getJrbThuocUCMD_Co(),
                 this.node3.getJrbThuocUCMD_Khong(),
                 this.node3.getJrbTreSSXNcovid_Co(),
                 this.node3.getJrbTreSSXNcovid_Khong(),
                 this.node3.getJrbUngThu_Co(),
                 this.node3.getJrbUngThu_Khong(),
                 this.node3.getJtfSoTuanMT(),
                
                
                 this.node4.getJcobDGTTBL(),
                 this.node4.getJrbBuonNon_Co(),
                 this.node4.getJrbBuonNon_Khong(),
                 this.node4.getJrbCoGiat_Co(),
                 this.node4.getJrbCoGiat_Khong(),
                 this.node4.getJrbDKCL_Co(),
                 this.node4.getJrbDKCL_Khong(),
                 this.node4.getJrbDauBung_Co(),
                 this.node4.getJrbDauBung_Khong(),
                 this.node4.getJrbDauCo_Co(),
                 this.node4.getJrbDauCo_Khong(),
                 this.node4.getJrbDauDau_Co(),
                 this.node4.getJrbDauDau_Khong(),
                 this.node4.getJrbDauHong_Co(),
                 this.node4.getJrbDauHong_Khong(),
                 this.node4.getJrbDauKhop_Co(),
                 this.node4.getJrbDauKhop_Khong(),
                 this.node4.getJrbMatKhuuGiac_Co(),
                 this.node4.getJrbMatKhuuGiac_Khong(),
                 this.node4.getJrbMatViGiac_Co(),
                 this.node4.getJrbMatViGiac_Khong(),
                 this.node4.getJrbNoiHach_Co(),
                 this.node4.getJrbNoiHach_Khong(),
                 this.node4.getJrbSot_Co(),
                 this.node4.getJrbSot_Khong(),
                 this.node4.getJrbTTKhac_Co(),
                 this.node4.getJrbTTKhac_Khong(),
                 this.node4.getJrbXuatHuyet_Co(),
                 this.node4.getJrbXuatHuyet_Khong(),
                 this.node4.getJtfCanNang(),
                 this.node4.getJtfChieuCao(),
                 this.node4.getJtfChuanDoanTT(),
                 this.node4.getJtfDoBH_Oxi(),
                 this.node4.getJtfHuyetApTThu(),
                 this.node4.getJtfHuyetApTTruong(),
                 this.node4.getJtfNhietDo(),
                 this.node4.getJtfNhipTho(),
                 this.node4.getJtfNhipTim(),
                 this.node4.getJtfTTKhac(),
                
                 this.node5.getJdcNgayXN(),
                
                 this.node5.getJrbDauNguc_Co(),
                 this.node5.getJrbDauNguc_Khong(),
                 this.node5.getJrbGoiA_Co(),
                 this.node5.getJrbGoiA_Khong(),
                   this.node5.getJrbGoiB_Co(),
                 this.node5.getJrbGoiB_Khong(),
                   this.node5.getJrbGoiC_Co(),
                 this.node5.getJrbGoiC_Khong(),
                 this.node5.getJrbHoRaDom_Co(),
                 this.node5.getJrbHoRaDom_Khong(),
                 this.node5.getJrbHoRaMau_Co(),
                 this.node5.getJrbHoRaMau_Khong(),
                 this.node5.getJrbHo_Co(),
                 this.node5.getJrbHo_Khong(),
                 this.node5.getJrbKQ_AT(),
                 this.node5.getJrbKQ_DT(),
                 this.node5.getJrbKhoTho_Co(),
                 this.node5.getJrbKhoTho_Khong(),
                 this.node5.getJrbKhongTT_Co(),
                 this.node5.getJrbKhongTT_Khong(),
                 this.node5.getJrbKietSuc_Co(),
                 this.node5.getJrbKietSuc_Khong(),
                 this.node5.getJrbMatKG_Co(),
                 this.node5.getJrbMatKG_Khong(),
                 this.node5.getJrbMatVG_Co(),
                 this.node5.getJrbMatVG_Khong(),
                 this.node5.getJrbOnLanh_Co(),
                 this.node5.getJrbOnLanh_Khong(),
                 this.node5.getJrbTieuChay_Co(),
                 this.node5.getJrbTieuChay_Khong(),
                 this.node5.getJrbXN_Co(),
                 this.node5.getJrbXN_Khong(),
                 this.node5.getJtfDoBHOxi(),
                 this.node5.getJtfHuyetApTD(),
                 this.node5.getJtfHuyetApToiThieu(),
                 this.node5.getJtfMach(),
                 this.node5.getJtfNhietDo_QTDT(),
                 this.node5.getJtfNhipTho_QTDT());
                
                if (node1.getJtfHoTen().getText().length() == 0
               || node1.getJtfCMND_CCCD().getText().length() == 0
               || node1.getJtfNoiO().getText().length()== 0
               || node1.getJtfSDT().getText().length()== 0
               ||node4.getJtfNhietDo().getText().length()== 0
               ||node4.getJtfNhipTho().getText().length()== 0
               ||node4.getJtfNhipTim().getText().length()== 0
               ||node4.getJtfChieuCao().getText().length()== 0
               ||node4.getJtfCanNang().getText().length()== 0
               ||node4.getJtfChuanDoanTT().getText().length()== 0
                  
                    
                    ) {
                        JFrame frame4 = new JFrame();
                            frame.setBounds(0,0,100,50);
                            JOptionPane.showMessageDialog(frame,
                            "Vui lòng nhập dữ liệu bắt buộc!");
                }else {
                    try {
                        tt_cn.UpdateTT();
                        JFrame frame2 = new JFrame();
                        frame.setBounds(0,0,100,50);
                        JOptionPane.showMessageDialog(frame,
                        "Cập nhật thành công");
                        this.dispose(); 
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(CapNhat_Frame.class.getName()).log(Level.SEVERE, null, ex);
                            ex.printStackTrace();
                        JFrame frame2 = new JFrame();
                        frame.setBounds(0,0,100,50);
                        JOptionPane.showMessageDialog(frame,
                        "Cập nhật thất bại\n" +
                         ex.getMessage()
                            );
                    } catch (SQLException ex) {
                        Logger.getLogger(CapNhat_Frame.class.getName()).log(Level.SEVERE, null, ex);
                         ex.printStackTrace();
                        JFrame frame2 = new JFrame();
                        frame.setBounds(0,0,100,50);
                        JOptionPane.showMessageDialog(frame,
                        "Cập nhật thất bại\n" +
                         ex.getSQLState()+"\n"+
                         ex.getMessage()

                            );
                    }
                    
                    
				}
            }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapNhat_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapNhat_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapNhat_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapNhat_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
//            new CapNhat_Frame(this).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbBenhNen;
    private javax.swing.JLabel jlbQTDieuTri;
    private javax.swing.JLabel jlbTTCoBan;
    private javax.swing.JLabel jlbTiemVX;
    private javax.swing.JLabel jlbTinhTrang;
    private javax.swing.JPanel jpnBenhNen;
    private javax.swing.JPanel jpnQTDieuTri;
    private javax.swing.JPanel jpnTTCoBan;
    private javax.swing.JPanel jpnTiemVX;
    private javax.swing.JPanel jpnTinhTrang;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}
