/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.da.qlf0.view.CapNhat;

import com.toedter.calendar.JDateChooser;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author NDAT_UIT
 */
public class QTDieuTri_CapNhat extends javax.swing.JPanel {

    /**
     * Creates new form QTDieuTri_CapNhat
     */
    public QTDieuTri_CapNhat() {
        initComponents();
    }

    public JDateChooser getJdcNgayXN() {
        return jdcNgayXN;
    }

   

    public JRadioButton getJrbDauNguc_Co() {
        return jrbDauNguc_Co;
    }

    public JRadioButton getJrbDauNguc_Khong() {
        return jrbDauNguc_Khong;
    }

    public JRadioButton getJrbGoiA_Co() {
        return jrbGoiA_Co;
    }

    public JRadioButton getJrbGoiA_Khong() {
        return jrbGoiA_Khong;
    }

    public JRadioButton getJrbGoiB_Co() {
        return jrbGoiB_Co;
    }

    public JRadioButton getJrbGoiB_Khong() {
        return jrbGoiB_Khong;
    }

    public JRadioButton getJrbGoiC_Co() {
        return jrbGoiC_Co;
    }

    public JRadioButton getJrbGoiC_Khong() {
        return jrbGoiC_Khong;
    }

    public JRadioButton getJrbHoRaDom_Co() {
        return jrbHoRaDom_Co;
    }

    public JRadioButton getJrbHoRaDom_Khong() {
        return jrbHoRaDom_Khong;
    }

    public JRadioButton getJrbHoRaMau_Co() {
        return jrbHoRaMau_Co;
    }

    public JRadioButton getJrbHoRaMau_Khong() {
        return jrbHoRaMau_Khong;
    }

    public JRadioButton getJrbHo_Co() {
        return jrbHo_Co;
    }

    public JRadioButton getJrbHo_Khong() {
        return jrbHo_Khong;
    }

    public JRadioButton getJrbKQ_AT() {
        return jrbKQ_AT;
    }

    public JRadioButton getJrbKQ_DT() {
        return jrbKQ_DT;
    }

    public JRadioButton getJrbKhoTho_Co() {
        return jrbKhoTho_Co;
    }

    public JRadioButton getJrbKhoTho_Khong() {
        return jrbKhoTho_Khong;
    }

    public JRadioButton getJrbKhongTT_Co() {
        return jrbKhongTT_Co;
    }

    public JRadioButton getJrbKhongTT_Khong() {
        return jrbKhongTT_Khong;
    }

    public JRadioButton getJrbKietSuc_Co() {
        return jrbKietSuc_Co;
    }

    public JRadioButton getJrbKietSuc_Khong() {
        return jrbKietSuc_Khong;
    }

    public JRadioButton getJrbMatKG_Co() {
        return jrbMatKG_Co;
    }

    public JRadioButton getJrbMatKG_Khong() {
        return jrbMatKG_Khong;
    }

    public JRadioButton getJrbOnLanh_Co() {
        return jrbOnLanh_Co;
    }

    public JRadioButton getJrbOnLanh_Khong() {
        return jrbOnLanh_Khong;
    }

    public JRadioButton getJrbTieuChay_Co() {
        return jrbTieuChay_Co;
    }

    public JRadioButton getJrbTieuChay_Khong() {
        return jrbTieuChay_Khong;
    }

    public JRadioButton getJrbXN_Co() {
        return jrbXN_Co;
    }

    public JRadioButton getJrbXN_Khong() {
        return jrbXN_Khong;
    }

    public JRadioButton getJrbMatVG_Co() {
        return jrbMatVG_Co;
    }

    public JRadioButton getJrbMatVG_Khong() {
        return jrbMatVG_Khong;
    }

    public JTextField getJtfDoBHOxi() {
        return jtfDoBHOxi;
    }

    public JTextField getJtfHuyetApTD() {
        return jtfHuyetApTD;
    }

    public JTextField getJtfHuyetApToiThieu() {
        return jtfHuyetApToiThieu;
    }

    public JTextField getJtfMach() {
        return jtfMach;
    }

    public JTextField getJtfNhietDo_QTDT() {
        return jtfNhietDo_QTDT;
    }

    public JTextField getJtfNhipTho_QTDT() {
        return jtfNhipTho_QTDT;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnG_KietSuc = new javax.swing.ButtonGroup();
        btnG_HoRaDom = new javax.swing.ButtonGroup();
        btnG_MatViGiac = new javax.swing.ButtonGroup();
        btnG_TieuChay = new javax.swing.ButtonGroup();
        btnG_Ho = new javax.swing.ButtonGroup();
        btnG_OnLanh = new javax.swing.ButtonGroup();
        btnG_MatKhuuGiac = new javax.swing.ButtonGroup();
        btnG_HoRaMau = new javax.swing.ButtonGroup();
        btnG_DauNguc = new javax.swing.ButtonGroup();
        btnG_KhoTho = new javax.swing.ButtonGroup();
        btnG_KhongTT = new javax.swing.ButtonGroup();
        btnG_GoiA = new javax.swing.ButtonGroup();
        btnG_GoiB = new javax.swing.ButtonGroup();
        btnG_GoiC = new javax.swing.ButtonGroup();
        btnG_XN = new javax.swing.ButtonGroup();
        btnG_KQ = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jtfMach = new javax.swing.JTextField();
        jrbKietSuc_Co = new javax.swing.JRadioButton();
        jrbKietSuc_Khong = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtfHuyetApTD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jrbHoRaDom_Co = new javax.swing.JRadioButton();
        jrbHoRaDom_Khong = new javax.swing.JRadioButton();
        jrbMatVG_Co = new javax.swing.JRadioButton();
        jrbMatVG_Khong = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jrbHo_Co = new javax.swing.JRadioButton();
        jrbHo_Khong = new javax.swing.JRadioButton();
        jrbOnLanh_Co = new javax.swing.JRadioButton();
        jrbOnLanh_Khong = new javax.swing.JRadioButton();
        jrbMatKG_Co = new javax.swing.JRadioButton();
        jrbMatKG_Khong = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jrbDauNguc_Co = new javax.swing.JRadioButton();
        jrbDauNguc_Khong = new javax.swing.JRadioButton();
        jrbHoRaMau_Co = new javax.swing.JRadioButton();
        jrbHoRaMau_Khong = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        jrbTieuChay_Co = new javax.swing.JRadioButton();
        jrbTieuChay_Khong = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jrbKhongTT_Co = new javax.swing.JRadioButton();
        jrbKhongTT_Khong = new javax.swing.JRadioButton();
        jrbKhoTho_Co = new javax.swing.JRadioButton();
        jrbKhoTho_Khong = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jrbGoiB_Co = new javax.swing.JRadioButton();
        jrbGoiA_Co = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        jrbGoiA_Khong = new javax.swing.JRadioButton();
        jrbGoiB_Khong = new javax.swing.JRadioButton();
        jrbGoiC_Co = new javax.swing.JRadioButton();
        jrbGoiC_Khong = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jrbXN_Co = new javax.swing.JRadioButton();
        jrbXN_Khong = new javax.swing.JRadioButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jdcNgayXN = new com.toedter.calendar.JDateChooser();
        jtfNhipTho_QTDT = new javax.swing.JTextField();
        jtfNhietDo_QTDT = new javax.swing.JTextField();
        jtfDoBHOxi = new javax.swing.JTextField();
        jtfHuyetApToiThieu = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        jrbKQ_AT = new javax.swing.JRadioButton();
        jrbKQ_DT = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 41, 102));
        jLabel9.setText("TỔNG TRẠNG");

        jSeparator3.setBackground(new java.awt.Color(166, 166, 166));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(20, 20, 20));
        jLabel12.setText("Nhịp thở (lần/phút):");

        jtfMach.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfMach.setForeground(new java.awt.Color(20, 20, 20));
        jtfMach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfMach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMachActionPerformed(evt);
            }
        });

        jrbKietSuc_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_KietSuc.add(jrbKietSuc_Co);
        jrbKietSuc_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbKietSuc_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbKietSuc_Co.setText("Có");
        jrbKietSuc_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbKietSuc_CoActionPerformed(evt);
            }
        });

        jrbKietSuc_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_KietSuc.add(jrbKietSuc_Khong);
        jrbKietSuc_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbKietSuc_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbKietSuc_Khong.setSelected(true);
        jrbKietSuc_Khong.setText("Không");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(20, 20, 20));
        jLabel13.setText("Mạch: ");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(20, 20, 20));
        jLabel14.setText("Huyết áp tối đa (mmhg):");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(20, 20, 20));
        jLabel15.setText("Nhiệt độ (độ C): ");

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(20, 20, 20));
        jLabel16.setText("Độ bão hòa Oxy trong máu(%):");

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(20, 20, 20));
        jLabel18.setText("Huyết áp tối thiểu (mmhg):");

        jtfHuyetApTD.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfHuyetApTD.setForeground(new java.awt.Color(20, 20, 20));
        jtfHuyetApTD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfHuyetApTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfHuyetApTDActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 41, 102));
        jLabel10.setText("TRIỆU CHỨNG (NẾU CÓ)");

        jSeparator4.setBackground(new java.awt.Color(166, 166, 166));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(20, 20, 20));
        jLabel20.setText("Kiệt sức/ mệt mõi");

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(20, 20, 20));
        jLabel21.setText("Ho ra đờm");

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(20, 20, 20));
        jLabel22.setText("Mất vị giác");

        jrbHoRaDom_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_HoRaDom.add(jrbHoRaDom_Co);
        jrbHoRaDom_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbHoRaDom_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbHoRaDom_Co.setText("Có");
        jrbHoRaDom_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbHoRaDom_CoActionPerformed(evt);
            }
        });

        jrbHoRaDom_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_HoRaDom.add(jrbHoRaDom_Khong);
        jrbHoRaDom_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbHoRaDom_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbHoRaDom_Khong.setSelected(true);
        jrbHoRaDom_Khong.setText("Không");

        jrbMatVG_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MatViGiac.add(jrbMatVG_Co);
        jrbMatVG_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbMatVG_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbMatVG_Co.setText("Có");
        jrbMatVG_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMatVG_CoActionPerformed(evt);
            }
        });

        jrbMatVG_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MatViGiac.add(jrbMatVG_Khong);
        jrbMatVG_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbMatVG_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbMatVG_Khong.setSelected(true);
        jrbMatVG_Khong.setText("Không");

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(20, 20, 20));
        jLabel25.setText("Ho");

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(20, 20, 20));
        jLabel26.setText("Ớn lạnh");

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(20, 20, 20));
        jLabel27.setText("Mất khứu giác");

        jrbHo_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_Ho.add(jrbHo_Co);
        jrbHo_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbHo_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbHo_Co.setText("Có");
        jrbHo_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbHo_CoActionPerformed(evt);
            }
        });

        jrbHo_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_Ho.add(jrbHo_Khong);
        jrbHo_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbHo_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbHo_Khong.setSelected(true);
        jrbHo_Khong.setText("Không");

        jrbOnLanh_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_OnLanh.add(jrbOnLanh_Co);
        jrbOnLanh_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbOnLanh_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbOnLanh_Co.setText("Có");
        jrbOnLanh_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOnLanh_CoActionPerformed(evt);
            }
        });

        jrbOnLanh_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_OnLanh.add(jrbOnLanh_Khong);
        jrbOnLanh_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbOnLanh_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbOnLanh_Khong.setSelected(true);
        jrbOnLanh_Khong.setText("Không");

        jrbMatKG_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MatKhuuGiac.add(jrbMatKG_Co);
        jrbMatKG_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbMatKG_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbMatKG_Co.setText("Có");
        jrbMatKG_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMatKG_CoActionPerformed(evt);
            }
        });

        jrbMatKG_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MatKhuuGiac.add(jrbMatKG_Khong);
        jrbMatKG_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbMatKG_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbMatKG_Khong.setSelected(true);
        jrbMatKG_Khong.setText("Không");

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 41, 102));
        jLabel11.setText("TRIỆU CHỨNG CHUYỂN NẶNG");

        jSeparator5.setBackground(new java.awt.Color(166, 166, 166));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(20, 20, 20));
        jLabel23.setText("Ho ra máu");

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(20, 20, 20));
        jLabel24.setText("Đau tức ngực khéo dài");

        jrbDauNguc_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_DauNguc.add(jrbDauNguc_Co);
        jrbDauNguc_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbDauNguc_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbDauNguc_Co.setText("Có");
        jrbDauNguc_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDauNguc_CoActionPerformed(evt);
            }
        });

        jrbDauNguc_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_DauNguc.add(jrbDauNguc_Khong);
        jrbDauNguc_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbDauNguc_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbDauNguc_Khong.setSelected(true);
        jrbDauNguc_Khong.setText("Không");

        jrbHoRaMau_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_HoRaMau.add(jrbHoRaMau_Co);
        jrbHoRaMau_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbHoRaMau_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbHoRaMau_Co.setText("Có");
        jrbHoRaMau_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbHoRaMau_CoActionPerformed(evt);
            }
        });

        jrbHoRaMau_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_HoRaMau.add(jrbHoRaMau_Khong);
        jrbHoRaMau_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbHoRaMau_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbHoRaMau_Khong.setSelected(true);
        jrbHoRaMau_Khong.setText("Không");

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(20, 20, 20));
        jLabel29.setText("Tiêu chảy");

        jrbTieuChay_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_TieuChay.add(jrbTieuChay_Co);
        jrbTieuChay_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbTieuChay_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbTieuChay_Co.setText("Có");
        jrbTieuChay_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTieuChay_CoActionPerformed(evt);
            }
        });

        jrbTieuChay_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_TieuChay.add(jrbTieuChay_Khong);
        jrbTieuChay_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbTieuChay_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbTieuChay_Khong.setSelected(true);
        jrbTieuChay_Khong.setText("Không");

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(20, 20, 20));
        jLabel30.setText("Thở dốc hoặc khó thở");

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(20, 20, 20));
        jLabel31.setText("Lơ mơ, không tỉnh táo");

        jrbKhongTT_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_KhongTT.add(jrbKhongTT_Co);
        jrbKhongTT_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbKhongTT_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbKhongTT_Co.setText("Có");
        jrbKhongTT_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbKhongTT_CoActionPerformed(evt);
            }
        });

        jrbKhongTT_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_KhongTT.add(jrbKhongTT_Khong);
        jrbKhongTT_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbKhongTT_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbKhongTT_Khong.setSelected(true);
        jrbKhongTT_Khong.setText("Không");

        jrbKhoTho_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_KhoTho.add(jrbKhoTho_Co);
        jrbKhoTho_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbKhoTho_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbKhoTho_Co.setText("Có");
        jrbKhoTho_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbKhoTho_CoActionPerformed(evt);
            }
        });

        jrbKhoTho_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_KhoTho.add(jrbKhoTho_Khong);
        jrbKhoTho_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbKhoTho_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbKhoTho_Khong.setSelected(true);
        jrbKhoTho_Khong.setText("Không");

        jLabel17.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 41, 102));
        jLabel17.setText("THUỐC SỬ DỤNG");

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(20, 20, 20));
        jLabel33.setText("Gói thuốc A (hạ sốt, vitamin)");

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(20, 20, 20));
        jLabel34.setText("Gói thuốc B (kháng đông, kháng viêm)");

        jrbGoiB_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_GoiB.add(jrbGoiB_Co);
        jrbGoiB_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbGoiB_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbGoiB_Co.setText("Có");
        jrbGoiB_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbGoiB_CoActionPerformed(evt);
            }
        });

        jrbGoiA_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_GoiA.add(jrbGoiA_Co);
        jrbGoiA_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbGoiA_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbGoiA_Co.setText("Có");
        jrbGoiA_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbGoiA_CoActionPerformed(evt);
            }
        });

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(20, 20, 20));
        jLabel35.setText("Gói thuốc C (Molnupiravir)");

        jrbGoiA_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_GoiA.add(jrbGoiA_Khong);
        jrbGoiA_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbGoiA_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbGoiA_Khong.setSelected(true);
        jrbGoiA_Khong.setText("Không");
        jrbGoiA_Khong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbGoiA_KhongActionPerformed(evt);
            }
        });

        jrbGoiB_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_GoiB.add(jrbGoiB_Khong);
        jrbGoiB_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbGoiB_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbGoiB_Khong.setSelected(true);
        jrbGoiB_Khong.setText("Không");
        jrbGoiB_Khong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbGoiB_KhongActionPerformed(evt);
            }
        });

        jrbGoiC_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_GoiC.add(jrbGoiC_Co);
        jrbGoiC_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbGoiC_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbGoiC_Co.setText("Có");
        jrbGoiC_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbGoiC_CoActionPerformed(evt);
            }
        });

        jrbGoiC_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_GoiC.add(jrbGoiC_Khong);
        jrbGoiC_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbGoiC_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbGoiC_Khong.setSelected(true);
        jrbGoiC_Khong.setText("Không");
        jrbGoiC_Khong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbGoiC_KhongActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 41, 102));
        jLabel19.setText("THÔNG TIN XÉT NGHIỆM");

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(20, 20, 20));
        jLabel36.setText("Xét nghiệm");

        jSeparator6.setBackground(new java.awt.Color(166, 166, 166));

        jrbXN_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_XN.add(jrbXN_Co);
        jrbXN_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbXN_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbXN_Co.setText("Có");
        jrbXN_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbXN_CoActionPerformed(evt);
            }
        });

        jrbXN_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_XN.add(jrbXN_Khong);
        jrbXN_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbXN_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbXN_Khong.setSelected(true);
        jrbXN_Khong.setText("Không");
        jrbXN_Khong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbXN_KhongActionPerformed(evt);
            }
        });

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(20, 20, 20));
        jLabel37.setText("Kết quả xét nghiệm");

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(20, 20, 20));
        jLabel38.setText("Ngày xét nghiệm");

        jdcNgayXN.setBackground(new java.awt.Color(255, 255, 255));
        jdcNgayXN.setForeground(new java.awt.Color(20, 20, 20));

        jtfNhipTho_QTDT.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfNhipTho_QTDT.setForeground(new java.awt.Color(20, 20, 20));
        jtfNhipTho_QTDT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfNhipTho_QTDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNhipTho_QTDTActionPerformed(evt);
            }
        });

        jtfNhietDo_QTDT.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfNhietDo_QTDT.setForeground(new java.awt.Color(20, 20, 20));
        jtfNhietDo_QTDT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfNhietDo_QTDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNhietDo_QTDTActionPerformed(evt);
            }
        });

        jtfDoBHOxi.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfDoBHOxi.setForeground(new java.awt.Color(20, 20, 20));
        jtfDoBHOxi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfDoBHOxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDoBHOxiActionPerformed(evt);
            }
        });

        jtfHuyetApToiThieu.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfHuyetApToiThieu.setForeground(new java.awt.Color(20, 20, 20));
        jtfHuyetApToiThieu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfHuyetApToiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfHuyetApToiThieuActionPerformed(evt);
            }
        });

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(20, 20, 20));
        jLabel40.setText("Kết quả:");

        jrbKQ_AT.setBackground(new java.awt.Color(255, 255, 255));
        btnG_KQ.add(jrbKQ_AT);
        jrbKQ_AT.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbKQ_AT.setForeground(new java.awt.Color(20, 20, 20));
        jrbKQ_AT.setText("Âm tính");
        jrbKQ_AT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbKQ_ATActionPerformed(evt);
            }
        });

        jrbKQ_DT.setBackground(new java.awt.Color(255, 255, 255));
        btnG_KQ.add(jrbKQ_DT);
        jrbKQ_DT.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbKQ_DT.setForeground(new java.awt.Color(20, 20, 20));
        jrbKQ_DT.setText("Dương tính");
        jrbKQ_DT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbKQ_DTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 1766, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 1766, Short.MAX_VALUE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 1766, Short.MAX_VALUE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 1766, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfMach)
                                    .addComponent(jtfNhipTho_QTDT)
                                    .addComponent(jtfHuyetApTD, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(130, 130, 130)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtfDoBHOxi, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfNhietDo_QTDT, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfHuyetApToiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel29))
                                        .addGap(110, 110, 110)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jrbHoRaDom_Co)
                                            .addComponent(jrbKietSuc_Co)
                                            .addComponent(jrbMatVG_Co)
                                            .addComponent(jrbTieuChay_Co))
                                        .addGap(120, 120, 120)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jrbHoRaDom_Khong)
                                            .addComponent(jrbKietSuc_Khong)
                                            .addComponent(jrbMatVG_Khong)
                                            .addComponent(jrbTieuChay_Khong)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel24))
                                        .addGap(110, 110, 110)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jrbDauNguc_Co)
                                            .addComponent(jrbHoRaMau_Co))
                                        .addGap(120, 120, 120)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jrbDauNguc_Khong)
                                            .addComponent(jrbHoRaMau_Khong))))
                                .addGap(150, 150, 150)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel26))
                                        .addGap(110, 110, 110)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jrbHo_Co)
                                            .addComponent(jrbOnLanh_Co)
                                            .addComponent(jrbMatKG_Co))
                                        .addGap(120, 120, 120)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jrbMatKG_Khong)
                                            .addComponent(jrbOnLanh_Khong)
                                            .addComponent(jrbHo_Khong)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel31)
                                            .addComponent(jLabel30))
                                        .addGap(110, 110, 110)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jrbKhongTT_Co)
                                            .addComponent(jrbKhoTho_Co))
                                        .addGap(120, 120, 120)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jrbKhongTT_Khong)
                                            .addComponent(jrbKhoTho_Khong)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel35))
                                .addGap(110, 110, 110)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrbGoiA_Co)
                                    .addComponent(jrbGoiC_Co))
                                .addGap(120, 120, 120)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrbGoiC_Khong)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jrbGoiA_Khong)
                                        .addGap(150, 150, 150)
                                        .addComponent(jLabel34)
                                        .addGap(110, 110, 110)
                                        .addComponent(jrbGoiB_Co)
                                        .addGap(120, 120, 120)
                                        .addComponent(jrbGoiB_Khong))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel37)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel36)
                                        .addGap(114, 114, 114)
                                        .addComponent(jrbXN_Co)
                                        .addGap(61, 61, 61)
                                        .addComponent(jrbXN_Khong)
                                        .addGap(87, 87, 87)
                                        .addComponent(jLabel38)))
                                .addGap(90, 90, 90)
                                .addComponent(jdcNgayXN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(jLabel40)
                                .addGap(43, 43, 43)
                                .addComponent(jrbKQ_DT)
                                .addGap(60, 60, 60)
                                .addComponent(jrbKQ_AT)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addGap(15, 15, 15)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jtfNhietDo_QTDT))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jtfDoBHOxi)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfMach)
                                .addGap(19, 19, 19)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNhipTho_QTDT))))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jtfHuyetApTD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jtfHuyetApToiThieu)))
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addGap(20, 20, 20)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jrbKietSuc_Co)
                    .addComponent(jrbKietSuc_Khong)
                    .addComponent(jrbHo_Co)
                    .addComponent(jrbHo_Khong)
                    .addComponent(jLabel25))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbHoRaDom_Co)
                    .addComponent(jrbHoRaDom_Khong)
                    .addComponent(jLabel26)
                    .addComponent(jrbOnLanh_Co)
                    .addComponent(jrbOnLanh_Khong)
                    .addComponent(jLabel21))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbMatVG_Co)
                    .addComponent(jrbMatVG_Khong)
                    .addComponent(jLabel27)
                    .addComponent(jrbMatKG_Co)
                    .addComponent(jrbMatKG_Khong)
                    .addComponent(jLabel22))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbTieuChay_Khong)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrbTieuChay_Co)
                        .addComponent(jLabel29)))
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jrbKhoTho_Co)
                            .addComponent(jrbKhoTho_Khong))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jrbKhongTT_Co)
                                .addComponent(jrbKhongTT_Khong))
                            .addComponent(jLabel31)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbHoRaMau_Co)
                            .addComponent(jrbHoRaMau_Khong))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbDauNguc_Co)
                            .addComponent(jrbDauNguc_Khong)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel24)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jrbGoiA_Co)
                    .addComponent(jrbGoiA_Khong)
                    .addComponent(jLabel34)
                    .addComponent(jrbGoiB_Co)
                    .addComponent(jrbGoiB_Khong))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jrbGoiC_Co)
                    .addComponent(jrbGoiC_Khong))
                .addGap(20, 20, 20)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel36)
                        .addComponent(jrbXN_Co)
                        .addComponent(jrbXN_Khong)
                        .addComponent(jLabel38))
                    .addComponent(jdcNgayXN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel40)
                        .addComponent(jrbKQ_AT)
                        .addComponent(jrbKQ_DT)))
                .addGap(213, 213, 213)
                .addComponent(jLabel37)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 20, 20));
        jLabel2.setText("QUÁ TRÌNH ĐIỀU TRỊ TẠI NHÀ");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(713, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(722, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfHuyetApToiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfHuyetApToiThieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfHuyetApToiThieuActionPerformed

    private void jtfDoBHOxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDoBHOxiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDoBHOxiActionPerformed

    private void jtfNhietDo_QTDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNhietDo_QTDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNhietDo_QTDTActionPerformed

    private void jtfNhipTho_QTDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNhipTho_QTDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNhipTho_QTDTActionPerformed

    private void jrbXN_KhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbXN_KhongActionPerformed
        // TODO add your handling code here:
        jrbKQ_AT.setEnabled(false);
        jrbKQ_DT.setEnabled(false);
    }//GEN-LAST:event_jrbXN_KhongActionPerformed

    private void jrbXN_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbXN_CoActionPerformed
        // TODO add your handling code here:
        jrbKQ_AT.setEnabled(true);
        jrbKQ_DT.setEnabled(true);
    }//GEN-LAST:event_jrbXN_CoActionPerformed

    private void jrbGoiC_KhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbGoiC_KhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbGoiC_KhongActionPerformed

    private void jrbGoiC_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbGoiC_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbGoiC_CoActionPerformed

    private void jrbGoiB_KhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbGoiB_KhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbGoiB_KhongActionPerformed

    private void jrbGoiA_KhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbGoiA_KhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbGoiA_KhongActionPerformed

    private void jrbGoiA_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbGoiA_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbGoiA_CoActionPerformed

    private void jrbGoiB_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbGoiB_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbGoiB_CoActionPerformed

    private void jrbKhoTho_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbKhoTho_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbKhoTho_CoActionPerformed

    private void jrbKhongTT_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbKhongTT_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbKhongTT_CoActionPerformed

    private void jrbTieuChay_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTieuChay_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbTieuChay_CoActionPerformed

    private void jrbHoRaMau_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbHoRaMau_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbHoRaMau_CoActionPerformed

    private void jrbDauNguc_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDauNguc_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbDauNguc_CoActionPerformed

    private void jrbMatKG_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMatKG_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMatKG_CoActionPerformed

    private void jrbOnLanh_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOnLanh_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbOnLanh_CoActionPerformed

    private void jrbHo_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbHo_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbHo_CoActionPerformed

    private void jrbMatVG_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMatVG_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMatVG_CoActionPerformed

    private void jrbHoRaDom_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbHoRaDom_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbHoRaDom_CoActionPerformed

    private void jtfHuyetApTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfHuyetApTDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfHuyetApTDActionPerformed

    private void jrbKietSuc_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbKietSuc_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbKietSuc_CoActionPerformed

    private void jtfMachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMachActionPerformed

    private void jrbKQ_ATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbKQ_ATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbKQ_ATActionPerformed

    private void jrbKQ_DTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbKQ_DTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbKQ_DTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnG_DauNguc;
    private javax.swing.ButtonGroup btnG_GoiA;
    private javax.swing.ButtonGroup btnG_GoiB;
    private javax.swing.ButtonGroup btnG_GoiC;
    private javax.swing.ButtonGroup btnG_Ho;
    private javax.swing.ButtonGroup btnG_HoRaDom;
    private javax.swing.ButtonGroup btnG_HoRaMau;
    private javax.swing.ButtonGroup btnG_KQ;
    private javax.swing.ButtonGroup btnG_KhoTho;
    private javax.swing.ButtonGroup btnG_KhongTT;
    private javax.swing.ButtonGroup btnG_KietSuc;
    private javax.swing.ButtonGroup btnG_MatKhuuGiac;
    private javax.swing.ButtonGroup btnG_MatViGiac;
    private javax.swing.ButtonGroup btnG_OnLanh;
    private javax.swing.ButtonGroup btnG_TieuChay;
    private javax.swing.ButtonGroup btnG_XN;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private com.toedter.calendar.JDateChooser jdcNgayXN;
    private javax.swing.JRadioButton jrbDauNguc_Co;
    private javax.swing.JRadioButton jrbDauNguc_Khong;
    private javax.swing.JRadioButton jrbGoiA_Co;
    private javax.swing.JRadioButton jrbGoiA_Khong;
    private javax.swing.JRadioButton jrbGoiB_Co;
    private javax.swing.JRadioButton jrbGoiB_Khong;
    private javax.swing.JRadioButton jrbGoiC_Co;
    private javax.swing.JRadioButton jrbGoiC_Khong;
    private javax.swing.JRadioButton jrbHoRaDom_Co;
    private javax.swing.JRadioButton jrbHoRaDom_Khong;
    private javax.swing.JRadioButton jrbHoRaMau_Co;
    private javax.swing.JRadioButton jrbHoRaMau_Khong;
    private javax.swing.JRadioButton jrbHo_Co;
    private javax.swing.JRadioButton jrbHo_Khong;
    private javax.swing.JRadioButton jrbKQ_AT;
    private javax.swing.JRadioButton jrbKQ_DT;
    private javax.swing.JRadioButton jrbKhoTho_Co;
    private javax.swing.JRadioButton jrbKhoTho_Khong;
    private javax.swing.JRadioButton jrbKhongTT_Co;
    private javax.swing.JRadioButton jrbKhongTT_Khong;
    private javax.swing.JRadioButton jrbKietSuc_Co;
    private javax.swing.JRadioButton jrbKietSuc_Khong;
    private javax.swing.JRadioButton jrbMatKG_Co;
    private javax.swing.JRadioButton jrbMatKG_Khong;
    private javax.swing.JRadioButton jrbMatVG_Co;
    private javax.swing.JRadioButton jrbMatVG_Khong;
    private javax.swing.JRadioButton jrbOnLanh_Co;
    private javax.swing.JRadioButton jrbOnLanh_Khong;
    private javax.swing.JRadioButton jrbTieuChay_Co;
    private javax.swing.JRadioButton jrbTieuChay_Khong;
    private javax.swing.JRadioButton jrbXN_Co;
    private javax.swing.JRadioButton jrbXN_Khong;
    private javax.swing.JTextField jtfDoBHOxi;
    private javax.swing.JTextField jtfHuyetApTD;
    private javax.swing.JTextField jtfHuyetApToiThieu;
    private javax.swing.JTextField jtfMach;
    private javax.swing.JTextField jtfNhietDo_QTDT;
    private javax.swing.JTextField jtfNhipTho_QTDT;
    // End of variables declaration//GEN-END:variables
}
