/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.da.qlf0.view.CapNhat;

import com.da.qlf0.view.GUI_ThemBN.*;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Minh Cuong
 */
public class TinhTrangTT_CapNhat extends javax.swing.JPanel {

    /**
     * Creates new form TinhTrangTT_ThemBN
     */
    public TinhTrangTT_CapNhat() {
        initComponents();
    }

    public JComboBox<String> getJcobDGTTBL() {
        return jcobDGTTBL;
    }

    public JRadioButton getJrbDauDau_Co() {
        return jrbDauDau_Co;
    }

    public JRadioButton getJrbDauDau_Khong() {
        return jrbDauDau_Khong;
    }

    public JRadioButton getJrbBuonNon_Co() {
        return jrbBuonNon_Co;
    }

    public JRadioButton getJrbBuonNon_Khong() {
        return jrbBuonNon_Khong;
    }

    public JRadioButton getJrbCoGiat_Co() {
        return jrbCoGiat_Co;
    }

    public JRadioButton getJrbCoGiat_Khong() {
        return jrbCoGiat_Khong;
    }

    public JRadioButton getJrbDauBung_Co() {
        return jrbDauBung_Co;
    }

    public JRadioButton getJrbDauBung_Khong() {
        return jrbDauBung_Khong;
    }

    public JRadioButton getJrbDauCo_Co() {
        return jrbDauCo_Co;
    }

    public JRadioButton getJrbDauCo_Khong() {
        return jrbDauCo_Khong;
    }

    public JRadioButton getJrbDauHong_Co() {
        return jrbDauHong_Co;
    }

    public JRadioButton getJrbDauHong_Khong() {
        return jrbDauHong_Khong;
    }

    public JRadioButton getJrbDauKhop_Co() {
        return jrbDauKhop_Co;
    }

    public JRadioButton getJrbDauKhop_Khong() {
        return jrbDauKhop_Khong;
    }

    public JRadioButton getJrbMatKhuuGiac_Co() {
        return jrbMatKhuuGiac_Co;
    }

    public JRadioButton getJrbMatKhuuGiac_Khong() {
        return jrbMatKhuuGiac_Khong;
    }

    public JRadioButton getJrbMatViGiac_Co() {
        return jrbMatViGiac_Co;
    }

    public JRadioButton getJrbMatViGiac_Khong() {
        return jrbMatViGiac_Khong;
    }

    public JRadioButton getJrbNoiHach_Co() {
        return jrbNoiHach_Co;
    }

    public JRadioButton getJrbNoiHach_Khong() {
        return jrbNoiHach_Khong;
    }

    public JRadioButton getJrbSot_Co() {
        return jrbSot_Co;
    }

    public JRadioButton getJrbSot_Khong() {
        return jrbSot_Khong;
    }

    public JRadioButton getJrbTTKhac_Co() {
        return jrbTTKhac_Co;
    }

    public JRadioButton getJrbTTKhac_Khong() {
        return jrbTTKhac_Khong;
    }

    public JRadioButton getJrbXuatHuyet_Co() {
        return jrbXuatHuyet_Co;
    }

    public JRadioButton getJrbXuatHuyet_Khong() {
        return jrbXuatHuyet_Khong;
    }

    public JTextField getJtfCanNang() {
        return jtfCanNang;
    }

    public JTextField getJtfChieuCao() {
        return jtfChieuCao;
    }

    public JTextField getJtfChuanDoanTT() {
        return jtfChuanDoanTT;
    }

    public JTextField getJtfDoBH_Oxi() {
        return jtfDoBH_Oxi;
    }

    public JTextField getJtfHuyetApTThu() {
        return jtfHuyetApTThu;
    }

    public JTextField getJtfHuyetApTTruong() {
        return jtfHuyetApTTruong;
    }

    public JTextField getJtfNhietDo() {
        return jtfNhietDo;
    }

    public JTextField getJtfNhipTho() {
        return jtfNhipTho;
    }

    public JTextField getJtfNhipTim() {
        return jtfNhipTim;
    }

    public JTextField getJtfTTKhac() {
        return jtfTTKhac;
    }

    public JRadioButton getJrbDKCL_Co() {
        return jrbDKCL_Co;
    }

    public JRadioButton getJrbDKCL_Khong() {
        return jrbDKCL_Khong;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnG_Sot = new javax.swing.ButtonGroup();
        btnG_DauHong = new javax.swing.ButtonGroup();
        btnG_NoiHach = new javax.swing.ButtonGroup();
        btnG_MatKG = new javax.swing.ButtonGroup();
        btnG_CoGiat = new javax.swing.ButtonGroup();
        btnG_XuatHuyet = new javax.swing.ButtonGroup();
        btnG_DauCo = new javax.swing.ButtonGroup();
        btnG_DauKhop = new javax.swing.ButtonGroup();
        btnG_DauBung = new javax.swing.ButtonGroup();
        btnG_MatVG = new javax.swing.ButtonGroup();
        btnG_BuonNon = new javax.swing.ButtonGroup();
        btnG_TTkhac = new javax.swing.ButtonGroup();
        btnG_DuDKCL = new javax.swing.ButtonGroup();
        btnG_DauDau = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jtfNhietDo = new javax.swing.JTextField();
        jrbSot_Co = new javax.swing.JRadioButton();
        jrbSot_Khong = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jtfNhipTim = new javax.swing.JTextField();
        jtfDoBH_Oxi = new javax.swing.JTextField();
        jtfNhipTho = new javax.swing.JTextField();
        jtfHuyetApTTruong = new javax.swing.JTextField();
        jtfChieuCao = new javax.swing.JTextField();
        jtfHuyetApTThu = new javax.swing.JTextField();
        jtfCanNang = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jrbDauHong_Co = new javax.swing.JRadioButton();
        jrbDauHong_Khong = new javax.swing.JRadioButton();
        jrbNoiHach_Co = new javax.swing.JRadioButton();
        jrbNoiHach_Khong = new javax.swing.JRadioButton();
        jrbMatKhuuGiac_Co = new javax.swing.JRadioButton();
        jrbMatKhuuGiac_Khong = new javax.swing.JRadioButton();
        jrbCoGiat_Co = new javax.swing.JRadioButton();
        jrbCoGiat_Khong = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jrbDauCo_Co = new javax.swing.JRadioButton();
        jrbDauCo_Khong = new javax.swing.JRadioButton();
        jrbDauKhop_Co = new javax.swing.JRadioButton();
        jrbDauKhop_Khong = new javax.swing.JRadioButton();
        jrbDauBung_Co = new javax.swing.JRadioButton();
        jrbDauBung_Khong = new javax.swing.JRadioButton();
        jrbMatViGiac_Co = new javax.swing.JRadioButton();
        jrbMatViGiac_Khong = new javax.swing.JRadioButton();
        jrbBuonNon_Co = new javax.swing.JRadioButton();
        jrbBuonNon_Khong = new javax.swing.JRadioButton();
        jrbTTKhac_Co = new javax.swing.JRadioButton();
        jrbTTKhac_Khong = new javax.swing.JRadioButton();
        jLabel32 = new javax.swing.JLabel();
        jtfTTKhac = new javax.swing.JTextField();
        jrbXuatHuyet_Co = new javax.swing.JRadioButton();
        jrbXuatHuyet_Khong = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jtfChuanDoanTT = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jcobDGTTBL = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jrbDKCL_Co = new javax.swing.JRadioButton();
        jrbDKCL_Khong = new javax.swing.JRadioButton();
        jLabel36 = new javax.swing.JLabel();
        jrbDauDau_Co = new javax.swing.JRadioButton();
        jrbDauDau_Khong = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(null);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(20, 20, 20));
        jLabel1.setText("TÌNH TRẠNG LÚC TIẾP NHẬN");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(680, 680, 680)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 41, 102));
        jLabel9.setText("TỔNG TRẠNG");

        jSeparator3.setBackground(new java.awt.Color(166, 166, 166));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(20, 20, 20));
        jLabel12.setText("Nhiệt tim (lần/phút)*:");

        jtfNhietDo.setBackground(new java.awt.Color(255, 255, 255));
        jtfNhietDo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfNhietDo.setForeground(new java.awt.Color(20, 20, 20));
        jtfNhietDo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfNhietDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNhietDoActionPerformed(evt);
            }
        });

        jrbSot_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_Sot.add(jrbSot_Co);
        jrbSot_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbSot_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbSot_Co.setText("Có");
        jrbSot_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSot_CoActionPerformed(evt);
            }
        });

        jrbSot_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_Sot.add(jrbSot_Khong);
        jrbSot_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbSot_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbSot_Khong.setSelected(true);
        jrbSot_Khong.setText("Không");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(20, 20, 20));
        jLabel13.setText("Nhiệt độ (độ C)*:");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(20, 20, 20));
        jLabel14.setText("Nhịp thở (lần/phút)*:");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(20, 20, 20));
        jLabel15.setText("Huyết áp tâm thu(mmHg):");

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(20, 20, 20));
        jLabel16.setText("Huyết áp tâm trương(mmHg):");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(20, 20, 20));
        jLabel17.setText("Độ bão hòa Oxy trong máu(%):");

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(20, 20, 20));
        jLabel18.setText("Chiều cao(cm):");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(20, 20, 20));
        jLabel19.setText("Cân nặng(kg):");

        jtfNhipTim.setBackground(new java.awt.Color(255, 255, 255));
        jtfNhipTim.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfNhipTim.setForeground(new java.awt.Color(20, 20, 20));
        jtfNhipTim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfNhipTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNhipTimActionPerformed(evt);
            }
        });

        jtfDoBH_Oxi.setBackground(new java.awt.Color(255, 255, 255));
        jtfDoBH_Oxi.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfDoBH_Oxi.setForeground(new java.awt.Color(20, 20, 20));
        jtfDoBH_Oxi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfDoBH_Oxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDoBH_OxiActionPerformed(evt);
            }
        });

        jtfNhipTho.setBackground(new java.awt.Color(255, 255, 255));
        jtfNhipTho.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfNhipTho.setForeground(new java.awt.Color(20, 20, 20));
        jtfNhipTho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfNhipTho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNhipThoActionPerformed(evt);
            }
        });

        jtfHuyetApTTruong.setBackground(new java.awt.Color(255, 255, 255));
        jtfHuyetApTTruong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfHuyetApTTruong.setForeground(new java.awt.Color(20, 20, 20));
        jtfHuyetApTTruong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfHuyetApTTruong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfHuyetApTTruongActionPerformed(evt);
            }
        });

        jtfChieuCao.setBackground(new java.awt.Color(255, 255, 255));
        jtfChieuCao.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfChieuCao.setForeground(new java.awt.Color(20, 20, 20));
        jtfChieuCao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfChieuCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfChieuCaoActionPerformed(evt);
            }
        });

        jtfHuyetApTThu.setBackground(new java.awt.Color(255, 255, 255));
        jtfHuyetApTThu.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfHuyetApTThu.setForeground(new java.awt.Color(20, 20, 20));
        jtfHuyetApTThu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfHuyetApTThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfHuyetApTThuActionPerformed(evt);
            }
        });

        jtfCanNang.setBackground(new java.awt.Color(255, 255, 255));
        jtfCanNang.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfCanNang.setForeground(new java.awt.Color(20, 20, 20));
        jtfCanNang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfCanNang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCanNangActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 41, 102));
        jLabel10.setText("TRIỆU CHỨNG TẠI THỜI ĐIỂM TIẾP NHẬN");

        jSeparator4.setBackground(new java.awt.Color(166, 166, 166));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(20, 20, 20));
        jLabel20.setText("Sốt:");

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(20, 20, 20));
        jLabel21.setText("Đau họng:");

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(20, 20, 20));
        jLabel22.setText("Nổi hạch ngoại vi:");

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(20, 20, 20));
        jLabel23.setText("Mất khứu giác:");

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(20, 20, 20));
        jLabel24.setText("Co giật:");

        jrbDauHong_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_DauHong.add(jrbDauHong_Co);
        jrbDauHong_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbDauHong_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbDauHong_Co.setText("Có");
        jrbDauHong_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDauHong_CoActionPerformed(evt);
            }
        });

        jrbDauHong_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_DauHong.add(jrbDauHong_Khong);
        jrbDauHong_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbDauHong_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbDauHong_Khong.setText("Không");

        jrbNoiHach_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_NoiHach.add(jrbNoiHach_Co);
        jrbNoiHach_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbNoiHach_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbNoiHach_Co.setText("Có");
        jrbNoiHach_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNoiHach_CoActionPerformed(evt);
            }
        });

        jrbNoiHach_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_NoiHach.add(jrbNoiHach_Khong);
        jrbNoiHach_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbNoiHach_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbNoiHach_Khong.setSelected(true);
        jrbNoiHach_Khong.setText("Không");

        jrbMatKhuuGiac_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MatKG.add(jrbMatKhuuGiac_Co);
        jrbMatKhuuGiac_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbMatKhuuGiac_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbMatKhuuGiac_Co.setText("Có");
        jrbMatKhuuGiac_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMatKhuuGiac_CoActionPerformed(evt);
            }
        });

        jrbMatKhuuGiac_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MatKG.add(jrbMatKhuuGiac_Khong);
        jrbMatKhuuGiac_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbMatKhuuGiac_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbMatKhuuGiac_Khong.setSelected(true);
        jrbMatKhuuGiac_Khong.setText("Không");

        jrbCoGiat_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_CoGiat.add(jrbCoGiat_Co);
        jrbCoGiat_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbCoGiat_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbCoGiat_Co.setText("Có");
        jrbCoGiat_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCoGiat_CoActionPerformed(evt);
            }
        });

        jrbCoGiat_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_CoGiat.add(jrbCoGiat_Khong);
        jrbCoGiat_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbCoGiat_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbCoGiat_Khong.setSelected(true);
        jrbCoGiat_Khong.setText("Không");

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(20, 20, 20));
        jLabel25.setText("Đau cơ:");

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(20, 20, 20));
        jLabel26.setText("Đau khớp:");

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(20, 20, 20));
        jLabel27.setText("Đau bụng:");

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(20, 20, 20));
        jLabel28.setText("Mất vị giác:");

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(20, 20, 20));
        jLabel29.setText("Buồn nôn:");

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(20, 20, 20));
        jLabel30.setText("Xuất huyết:");

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(20, 20, 20));
        jLabel31.setText("Triệu chứng khác:");

        jrbDauCo_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_DauCo.add(jrbDauCo_Co);
        jrbDauCo_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbDauCo_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbDauCo_Co.setText("Có");
        jrbDauCo_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDauCo_CoActionPerformed(evt);
            }
        });

        jrbDauCo_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_DauCo.add(jrbDauCo_Khong);
        jrbDauCo_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbDauCo_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbDauCo_Khong.setSelected(true);
        jrbDauCo_Khong.setText("Không");

        jrbDauKhop_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_DauKhop.add(jrbDauKhop_Co);
        jrbDauKhop_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbDauKhop_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbDauKhop_Co.setText("Có");
        jrbDauKhop_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDauKhop_CoActionPerformed(evt);
            }
        });

        jrbDauKhop_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_DauKhop.add(jrbDauKhop_Khong);
        jrbDauKhop_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbDauKhop_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbDauKhop_Khong.setSelected(true);
        jrbDauKhop_Khong.setText("Không");

        jrbDauBung_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_DauBung.add(jrbDauBung_Co);
        jrbDauBung_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbDauBung_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbDauBung_Co.setText("Có");
        jrbDauBung_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDauBung_CoActionPerformed(evt);
            }
        });

        jrbDauBung_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_DauBung.add(jrbDauBung_Khong);
        jrbDauBung_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbDauBung_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbDauBung_Khong.setSelected(true);
        jrbDauBung_Khong.setText("Không");

        jrbMatViGiac_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MatVG.add(jrbMatViGiac_Co);
        jrbMatViGiac_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbMatViGiac_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbMatViGiac_Co.setText("Có");
        jrbMatViGiac_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMatViGiac_CoActionPerformed(evt);
            }
        });

        jrbMatViGiac_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MatVG.add(jrbMatViGiac_Khong);
        jrbMatViGiac_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbMatViGiac_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbMatViGiac_Khong.setSelected(true);
        jrbMatViGiac_Khong.setText("Không");

        jrbBuonNon_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_BuonNon.add(jrbBuonNon_Co);
        jrbBuonNon_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbBuonNon_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbBuonNon_Co.setText("Có");
        jrbBuonNon_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbBuonNon_CoActionPerformed(evt);
            }
        });

        jrbBuonNon_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_BuonNon.add(jrbBuonNon_Khong);
        jrbBuonNon_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbBuonNon_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbBuonNon_Khong.setSelected(true);
        jrbBuonNon_Khong.setText("Không");

        jrbTTKhac_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_TTkhac.add(jrbTTKhac_Co);
        jrbTTKhac_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbTTKhac_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbTTKhac_Co.setText("Có");
        jrbTTKhac_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTTKhac_CoActionPerformed(evt);
            }
        });

        jrbTTKhac_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_TTkhac.add(jrbTTKhac_Khong);
        jrbTTKhac_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbTTKhac_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbTTKhac_Khong.setSelected(true);
        jrbTTKhac_Khong.setText("Không");

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(20, 20, 20));
        jLabel32.setText("Nếu CÓ, ghi cụ thể*:");

        jtfTTKhac.setBackground(new java.awt.Color(255, 255, 255));
        jtfTTKhac.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfTTKhac.setForeground(new java.awt.Color(20, 20, 20));
        jtfTTKhac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfTTKhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTTKhacActionPerformed(evt);
            }
        });

        jrbXuatHuyet_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_XuatHuyet.add(jrbXuatHuyet_Co);
        jrbXuatHuyet_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbXuatHuyet_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbXuatHuyet_Co.setText("Có");
        jrbXuatHuyet_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbXuatHuyet_CoActionPerformed(evt);
            }
        });

        jrbXuatHuyet_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_XuatHuyet.add(jrbXuatHuyet_Khong);
        jrbXuatHuyet_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbXuatHuyet_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbXuatHuyet_Khong.setSelected(true);
        jrbXuatHuyet_Khong.setText("Không");

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 41, 102));
        jLabel11.setText("ĐÁNH GIÁ SƠ LƯỢC");

        jSeparator5.setBackground(new java.awt.Color(166, 166, 166));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(20, 20, 20));
        jLabel33.setText("Chẩn đoán lúc tiếp nhận:");

        jtfChuanDoanTT.setBackground(new java.awt.Color(255, 255, 255));
        jtfChuanDoanTT.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfChuanDoanTT.setForeground(new java.awt.Color(20, 20, 20));
        jtfChuanDoanTT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfChuanDoanTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfChuanDoanTTActionPerformed(evt);
            }
        });

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(20, 20, 20));
        jLabel34.setText("Đánh giá tình trạng bệnh lý COVID-19:");

        jcobDGTTBL.setBackground(new java.awt.Color(255, 255, 255));
        jcobDGTTBL.setForeground(new java.awt.Color(20, 20, 20));
        jcobDGTTBL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(20, 20, 20));
        jLabel35.setText("Đánh giá đủ điều kiện cách ly tại nhà:");

        jrbDKCL_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_DuDKCL.add(jrbDKCL_Co);
        jrbDKCL_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbDKCL_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbDKCL_Co.setSelected(true);
        jrbDKCL_Co.setText("Đủ");
        jrbDKCL_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDKCL_CoActionPerformed(evt);
            }
        });

        jrbDKCL_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_DuDKCL.add(jrbDKCL_Khong);
        jrbDKCL_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbDKCL_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbDKCL_Khong.setText("Không");

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(20, 20, 20));
        jLabel36.setText("Đau Đầu:");

        jrbDauDau_Co.setBackground(new java.awt.Color(255, 255, 255));
        btnG_DauDau.add(jrbDauDau_Co);
        jrbDauDau_Co.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbDauDau_Co.setForeground(new java.awt.Color(20, 20, 20));
        jrbDauDau_Co.setSelected(true);
        jrbDauDau_Co.setText("Có");
        jrbDauDau_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDauDau_CoActionPerformed(evt);
            }
        });

        jrbDauDau_Khong.setBackground(new java.awt.Color(255, 255, 255));
        btnG_DauDau.add(jrbDauDau_Khong);
        jrbDauDau_Khong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbDauDau_Khong.setForeground(new java.awt.Color(20, 20, 20));
        jrbDauDau_Khong.setText("Không");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1766, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel17))
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfNhipTim, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfNhietDo, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfNhipTho, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfDoBH_Oxi, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(158, 158, 158)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfCanNang, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfChieuCao, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfHuyetApTThu, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfHuyetApTTruong, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 1766, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 1766, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel33)
                                .addGap(51, 51, 51)
                                .addComponent(jtfChuanDoanTT, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel35))
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jrbDKCL_Co)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jrbDKCL_Khong))
                                    .addComponent(jcobDGTTBL, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel30)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel24))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(102, 102, 102)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jrbDauHong_Co)
                                                    .addComponent(jrbSot_Co))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jrbNoiHach_Co, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jrbMatKhuuGiac_Co, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jrbCoGiat_Co, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jrbXuatHuyet_Co, javax.swing.GroupLayout.Alignment.TRAILING)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel36)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jrbDauDau_Co)))
                                .addGap(157, 157, 157)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jrbDauHong_Khong)
                                    .addComponent(jrbSot_Khong)
                                    .addComponent(jrbNoiHach_Khong)
                                    .addComponent(jrbMatKhuuGiac_Khong)
                                    .addComponent(jrbCoGiat_Khong)
                                    .addComponent(jrbXuatHuyet_Khong, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jrbDauDau_Khong))
                                .addGap(226, 226, 226)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel31)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel26)
                                                    .addGap(55, 55, 55))
                                                .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(jLabel28)
                                            .addComponent(jLabel29))
                                        .addGap(140, 140, 140)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jrbDauCo_Co)
                                            .addComponent(jrbDauKhop_Co)
                                            .addComponent(jrbMatViGiac_Co)
                                            .addComponent(jrbBuonNon_Co)
                                            .addComponent(jrbTTKhac_Co)
                                            .addComponent(jrbDauBung_Co))
                                        .addGap(168, 168, 168)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jrbDauBung_Khong)
                                            .addComponent(jrbTTKhac_Khong)
                                            .addComponent(jrbBuonNon_Khong)
                                            .addComponent(jrbMatViGiac_Khong)
                                            .addComponent(jrbDauKhop_Khong)
                                            .addComponent(jrbDauCo_Khong)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addGap(103, 103, 103)
                                        .addComponent(jtfTTKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel10)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jtfHuyetApTThu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(jtfHuyetApTTruong, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addComponent(jtfChieuCao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(jtfCanNang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfNhietDo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfNhipTim, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfNhipTho, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfDoBH_Oxi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))))
                .addGap(40, 40, 40)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jrbSot_Co)
                    .addComponent(jrbSot_Khong)
                    .addComponent(jrbDauCo_Co)
                    .addComponent(jrbDauCo_Khong)
                    .addComponent(jLabel25))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jrbDauHong_Co)
                                    .addComponent(jrbDauHong_Khong)
                                    .addComponent(jLabel26)
                                    .addComponent(jrbDauKhop_Co)
                                    .addComponent(jrbDauKhop_Khong)
                                    .addComponent(jLabel21))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jrbDauDau_Khong))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jrbDauBung_Co)
                                                .addComponent(jrbDauBung_Khong))
                                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addComponent(jrbDauDau_Co))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jrbNoiHach_Co)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbMatKhuuGiac_Co)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbCoGiat_Co))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jrbNoiHach_Khong))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jrbMatKhuuGiac_Khong))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jrbCoGiat_Khong)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jrbMatViGiac_Khong, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jrbBuonNon_Khong))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbTTKhac_Khong)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jrbXuatHuyet_Co)
                                    .addComponent(jrbXuatHuyet_Khong, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addComponent(jLabel11))
                            .addComponent(jtfTTKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrbMatViGiac_Co)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbBuonNon_Co)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jrbTTKhac_Co))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jtfChuanDoanTT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(jcobDGTTBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(jrbDKCL_Co)
                            .addComponent(jrbDKCL_Khong))))
                .addContainerGap(184, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNhietDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNhietDoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNhietDoActionPerformed

    private void jrbSot_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSot_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbSot_CoActionPerformed

    private void jtfNhipTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNhipTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNhipTimActionPerformed

    private void jtfDoBH_OxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDoBH_OxiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDoBH_OxiActionPerformed

    private void jtfNhipThoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNhipThoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNhipThoActionPerformed

    private void jtfHuyetApTTruongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfHuyetApTTruongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfHuyetApTTruongActionPerformed

    private void jtfChieuCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfChieuCaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfChieuCaoActionPerformed

    private void jtfHuyetApTThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfHuyetApTThuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfHuyetApTThuActionPerformed

    private void jtfCanNangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCanNangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCanNangActionPerformed

    private void jrbDauHong_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDauHong_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbDauHong_CoActionPerformed

    private void jrbNoiHach_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNoiHach_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbNoiHach_CoActionPerformed

    private void jrbMatKhuuGiac_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMatKhuuGiac_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMatKhuuGiac_CoActionPerformed

    private void jrbCoGiat_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCoGiat_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbCoGiat_CoActionPerformed

    private void jrbDauCo_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDauCo_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbDauCo_CoActionPerformed

    private void jrbDauKhop_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDauKhop_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbDauKhop_CoActionPerformed

    private void jrbDauBung_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDauBung_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbDauBung_CoActionPerformed

    private void jrbMatViGiac_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMatViGiac_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMatViGiac_CoActionPerformed

    private void jrbBuonNon_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbBuonNon_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbBuonNon_CoActionPerformed

    private void jrbTTKhac_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTTKhac_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbTTKhac_CoActionPerformed

    private void jtfTTKhacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTTKhacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTTKhacActionPerformed

    private void jrbXuatHuyet_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbXuatHuyet_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbXuatHuyet_CoActionPerformed

    private void jtfChuanDoanTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfChuanDoanTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfChuanDoanTTActionPerformed

    private void jrbDKCL_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDKCL_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbDKCL_CoActionPerformed

    private void jrbDauDau_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDauDau_CoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbDauDau_CoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnG_BuonNon;
    private javax.swing.ButtonGroup btnG_CoGiat;
    private javax.swing.ButtonGroup btnG_DauBung;
    private javax.swing.ButtonGroup btnG_DauCo;
    private javax.swing.ButtonGroup btnG_DauDau;
    private javax.swing.ButtonGroup btnG_DauHong;
    private javax.swing.ButtonGroup btnG_DauKhop;
    private javax.swing.ButtonGroup btnG_DuDKCL;
    private javax.swing.ButtonGroup btnG_MatKG;
    private javax.swing.ButtonGroup btnG_MatVG;
    private javax.swing.ButtonGroup btnG_NoiHach;
    private javax.swing.ButtonGroup btnG_Sot;
    private javax.swing.ButtonGroup btnG_TTkhac;
    private javax.swing.ButtonGroup btnG_XuatHuyet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JComboBox<String> jcobDGTTBL;
    private javax.swing.JRadioButton jrbBuonNon_Co;
    private javax.swing.JRadioButton jrbBuonNon_Khong;
    private javax.swing.JRadioButton jrbCoGiat_Co;
    private javax.swing.JRadioButton jrbCoGiat_Khong;
    private javax.swing.JRadioButton jrbDKCL_Co;
    private javax.swing.JRadioButton jrbDKCL_Khong;
    private javax.swing.JRadioButton jrbDauBung_Co;
    private javax.swing.JRadioButton jrbDauBung_Khong;
    private javax.swing.JRadioButton jrbDauCo_Co;
    private javax.swing.JRadioButton jrbDauCo_Khong;
    private javax.swing.JRadioButton jrbDauDau_Co;
    private javax.swing.JRadioButton jrbDauDau_Khong;
    private javax.swing.JRadioButton jrbDauHong_Co;
    private javax.swing.JRadioButton jrbDauHong_Khong;
    private javax.swing.JRadioButton jrbDauKhop_Co;
    private javax.swing.JRadioButton jrbDauKhop_Khong;
    private javax.swing.JRadioButton jrbMatKhuuGiac_Co;
    private javax.swing.JRadioButton jrbMatKhuuGiac_Khong;
    private javax.swing.JRadioButton jrbMatViGiac_Co;
    private javax.swing.JRadioButton jrbMatViGiac_Khong;
    private javax.swing.JRadioButton jrbNoiHach_Co;
    private javax.swing.JRadioButton jrbNoiHach_Khong;
    private javax.swing.JRadioButton jrbSot_Co;
    private javax.swing.JRadioButton jrbSot_Khong;
    private javax.swing.JRadioButton jrbTTKhac_Co;
    private javax.swing.JRadioButton jrbTTKhac_Khong;
    private javax.swing.JRadioButton jrbXuatHuyet_Co;
    private javax.swing.JRadioButton jrbXuatHuyet_Khong;
    private javax.swing.JTextField jtfCanNang;
    private javax.swing.JTextField jtfChieuCao;
    private javax.swing.JTextField jtfChuanDoanTT;
    private javax.swing.JTextField jtfDoBH_Oxi;
    private javax.swing.JTextField jtfHuyetApTThu;
    private javax.swing.JTextField jtfHuyetApTTruong;
    private javax.swing.JTextField jtfNhietDo;
    private javax.swing.JTextField jtfNhipTho;
    private javax.swing.JTextField jtfNhipTim;
    private javax.swing.JTextField jtfTTKhac;
    // End of variables declaration//GEN-END:variables
}
