/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.da.qlf0.view;

import com.da.qlf0.controller.PrintBenhAnController;
import com.da.qlf0.controller.TaoKQDieuTriController;
import com.toedter.calendar.JDateChooser;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;
import java.lang.Exception;

/**
 *
 * @author Minh Cuong
 */
public class KQDieuTri extends javax.swing.JPanel {

    /**
     * Creates new form TinhTrangTT_ThemBN
     */
    private JFrame frame2;
    private String MABN;
    public KQDieuTri(String MABN) {
        initComponents();
        JFrame frame = new JFrame();
        
        
        JScrollPane scrollp = new JScrollPane(this, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        frame.setResizable(true);
        frame.setLocationRelativeTo(null);
        frame.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        frame.setUndecorated(true);
                    frame.add(scrollp);
          
                    frame.validate();
                    frame.repaint();
                    frame.setVisible(true);
                    this.frame2=frame;
                    this.MABN=MABN;
    }

    public String getMABN() {
        return MABN;
    }

    public JComboBox<String> getJcobNoiTuVong() {
        return jcobNoiTuVong;
    }

    public JDateChooser getJdcNgayNhapVien() {
        return jdcNgayNhapVien;
    }

    public JDateChooser getJdcNgayTuVong() {
        return jdcNgayTuVong;
    }

    public JDateChooser getJdc_NgayKTCL() {
        return jdc_NgayKTCL;
    }

    public JDateChooser getJdc_NgayXNAT() {
        return jdc_NgayXNAT;
    }

    public JRadioButton getJrbCN_NV() {
        return jrbCN_NV;
    }

    public JRadioButton getJrbHTCL() {
        return jrbHTCL;
    }

    public JRadioButton getJrbKhac() {
        return jrbKhac;
    }

    public JRadioButton getJrbLiDoTV_BenhNen() {
        return jrbLiDoTV_BenhNen;
    }

    public JRadioButton getJrbLiDoTV_Covid() {
        return jrbLiDoTV_Covid;
    }

    public JRadioButton getJrbPCR() {
        return jrbPCR;
    }

    public JRadioButton getJrbTestNhanh() {
        return jrbTestNhanh;
    }

    public JRadioButton getJrbTuVong() {
        return jrbTuVong;
    }

    public JTextField getJtfKhacCuThe() {
        return jtfKhacCuThe;
    }

    public JTextField getJtfLidoTuVongKhac() {
        return jtfLidoTuVongKhac;
    }

    public JTextField getJtfLuuY() {
        return jtfLuuY;
    }

    public JTextField getJtfNoiTuVongKhac() {
        return jtfNoiTuVongKhac;
    }

    public JTextField getJtfTTkhiNV() {
        return jtfTTkhiNV;
    }

    public JTextField getJtfTenCSNV() {
        return jtfTenCSNV;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnG_LoaiXN = new javax.swing.ButtonGroup();
        bntG_TinhTrang = new javax.swing.ButtonGroup();
        btnG_LiDoTV = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtfKhacCuThe = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jtfTTkhiNV = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jrbCN_NV = new javax.swing.JRadioButton();
        jrbHTCL = new javax.swing.JRadioButton();
        jrbTuVong = new javax.swing.JRadioButton();
        jrbKhac = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jdc_NgayKTCL = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jdc_NgayXNAT = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jrbTestNhanh = new javax.swing.JRadioButton();
        jrbPCR = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jdcNgayNhapVien = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtfLuuY = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jtfTenCSNV = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jdcNgayTuVong = new com.toedter.calendar.JDateChooser();
        jLabel24 = new javax.swing.JLabel();
        jcobNoiTuVong = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jtfLidoTuVongKhac = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jrbLiDoTV_BenhNen = new javax.swing.JRadioButton();
        jrbLiDoTV_Covid = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        jtfNoiTuVongKhac = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(null);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(20, 20, 20));
        jLabel1.setText("KẾT QUẢ SAU ĐIỀU TRỊ TẠI NHÀ ");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/da/qlf0/images/previous.png"))); // NOI18N
        jButton3.setText("Trờ lại");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton3)
                .addGap(452, 452, 452)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jSeparator3.setBackground(new java.awt.Color(166, 166, 166));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(20, 20, 20));
        jLabel13.setText("Tình trạng:");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(20, 20, 20));
        jLabel15.setText("Khác cụ thể:");

        jtfKhacCuThe.setBackground(new java.awt.Color(255, 255, 255));
        jtfKhacCuThe.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfKhacCuThe.setForeground(new java.awt.Color(20, 20, 20));
        jtfKhacCuThe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfKhacCuThe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfKhacCuTheActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 41, 102));
        jLabel10.setText("HOÀN THÀNH CÁCH LY");

        jSeparator4.setBackground(new java.awt.Color(166, 166, 166));

        jtfTTkhiNV.setBackground(new java.awt.Color(255, 255, 255));
        jtfTTkhiNV.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfTTkhiNV.setForeground(new java.awt.Color(20, 20, 20));
        jtfTTkhiNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfTTkhiNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTTkhiNVActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 41, 102));
        jLabel11.setText("CHUYỂN NẶNG/ NHẬP VIỆN");

        jSeparator5.setBackground(new java.awt.Color(166, 166, 166));

        jrbCN_NV.setBackground(new java.awt.Color(255, 255, 255));
        bntG_TinhTrang.add(jrbCN_NV);
        jrbCN_NV.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbCN_NV.setForeground(new java.awt.Color(20, 20, 20));
        jrbCN_NV.setText("Chuyển nặng phải nhập viện");
        jrbCN_NV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCN_NVActionPerformed(evt);
            }
        });

        jrbHTCL.setBackground(new java.awt.Color(255, 255, 255));
        bntG_TinhTrang.add(jrbHTCL);
        jrbHTCL.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbHTCL.setForeground(new java.awt.Color(20, 20, 20));
        jrbHTCL.setText("Hoàn thành cách ly");
        jrbHTCL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbHTCLActionPerformed(evt);
            }
        });

        jrbTuVong.setBackground(new java.awt.Color(255, 255, 255));
        bntG_TinhTrang.add(jrbTuVong);
        jrbTuVong.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbTuVong.setForeground(new java.awt.Color(20, 20, 20));
        jrbTuVong.setText("Tử vong");
        jrbTuVong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTuVongActionPerformed(evt);
            }
        });

        jrbKhac.setBackground(new java.awt.Color(255, 255, 255));
        bntG_TinhTrang.add(jrbKhac);
        jrbKhac.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbKhac.setForeground(new java.awt.Color(20, 20, 20));
        jrbKhac.setText("Khác");
        jrbKhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbKhacActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(20, 20, 20));
        jLabel16.setText("Ngày kết thúc cách ly tại nhà:");

        jdc_NgayKTCL.setBackground(new java.awt.Color(255, 255, 255));
        jdc_NgayKTCL.setForeground(new java.awt.Color(20, 20, 20));
        jdc_NgayKTCL.setDateFormatString("dd-MM-yyyy\n\n\n");
        jdc_NgayKTCL.setEnabled(false);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(20, 20, 20));
        jLabel17.setText("Ngày xét nghiệm âm tính:");

        jdc_NgayXNAT.setBackground(new java.awt.Color(255, 255, 255));
        jdc_NgayXNAT.setForeground(new java.awt.Color(20, 20, 20));
        jdc_NgayXNAT.setDateFormatString("dd-MM-yyyy\n");

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(20, 20, 20));
        jLabel18.setText("Loại xét nghiệm:");

        jrbTestNhanh.setBackground(new java.awt.Color(255, 255, 255));
        btnG_LoaiXN.add(jrbTestNhanh);
        jrbTestNhanh.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbTestNhanh.setForeground(new java.awt.Color(20, 20, 20));
        jrbTestNhanh.setText("Test Nhanh");
        jrbTestNhanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTestNhanhActionPerformed(evt);
            }
        });

        jrbPCR.setBackground(new java.awt.Color(255, 255, 255));
        btnG_LoaiXN.add(jrbPCR);
        jrbPCR.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbPCR.setForeground(new java.awt.Color(20, 20, 20));
        jrbPCR.setText("PCR");
        jrbPCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPCRActionPerformed(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(20, 20, 20));
        jLabel19.setText("Ngày nhập viện:");

        jdcNgayNhapVien.setBackground(new java.awt.Color(255, 255, 255));
        jdcNgayNhapVien.setForeground(new java.awt.Color(20, 20, 20));
        jdcNgayNhapVien.setDateFormatString("dd-MM-yyyy\n");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(20, 20, 20));
        jLabel20.setText("Triệu chứng khi nhập viện:");

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(20, 20, 20));
        jLabel21.setText("Tên cơ sở nhập viện :");

        jtfLuuY.setBackground(new java.awt.Color(255, 255, 255));
        jtfLuuY.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfLuuY.setForeground(new java.awt.Color(20, 20, 20));
        jtfLuuY.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfLuuY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfLuuYActionPerformed(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(20, 20, 20));
        jLabel22.setText("Lưu ý với bệnh nhân:");

        jtfTenCSNV.setBackground(new java.awt.Color(255, 255, 255));
        jtfTenCSNV.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfTenCSNV.setForeground(new java.awt.Color(20, 20, 20));
        jtfTenCSNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfTenCSNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTenCSNVActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 41, 102));
        jLabel12.setText("TỬ VONG");

        jSeparator6.setBackground(new java.awt.Color(166, 166, 166));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(20, 20, 20));
        jLabel23.setText("Ngày từ vong:");

        jdcNgayTuVong.setBackground(new java.awt.Color(255, 255, 255));
        jdcNgayTuVong.setForeground(new java.awt.Color(20, 20, 20));
        jdcNgayTuVong.setDateFormatString("dd-MM-yyyy\n");

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(20, 20, 20));
        jLabel24.setText("Nơi tử vong:");

        jcobNoiTuVong.setBackground(new java.awt.Color(255, 255, 255));
        jcobNoiTuVong.setForeground(new java.awt.Color(20, 20, 20));
        jcobNoiTuVong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhà riêng", "Bệnh viện", "Không rõ" }));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(20, 20, 20));
        jLabel25.setText("Nơi tử vong khác:");

        jtfLidoTuVongKhac.setBackground(new java.awt.Color(255, 255, 255));
        jtfLidoTuVongKhac.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfLidoTuVongKhac.setForeground(new java.awt.Color(20, 20, 20));
        jtfLidoTuVongKhac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfLidoTuVongKhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfLidoTuVongKhacActionPerformed(evt);
            }
        });

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(20, 20, 20));
        jLabel26.setText("Lý do tử vong:");

        jrbLiDoTV_BenhNen.setBackground(new java.awt.Color(255, 255, 255));
        btnG_LiDoTV.add(jrbLiDoTV_BenhNen);
        jrbLiDoTV_BenhNen.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbLiDoTV_BenhNen.setForeground(new java.awt.Color(20, 20, 20));
        jrbLiDoTV_BenhNen.setText("Bệnh nền tiến triển");
        jrbLiDoTV_BenhNen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbLiDoTV_BenhNenActionPerformed(evt);
            }
        });

        jrbLiDoTV_Covid.setBackground(new java.awt.Color(255, 255, 255));
        btnG_LiDoTV.add(jrbLiDoTV_Covid);
        jrbLiDoTV_Covid.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbLiDoTV_Covid.setForeground(new java.awt.Color(20, 20, 20));
        jrbLiDoTV_Covid.setText("COVID-19");
        jrbLiDoTV_Covid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbLiDoTV_CovidActionPerformed(evt);
            }
        });

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(20, 20, 20));
        jLabel27.setText("Lý do tử vong khác:");

        jtfNoiTuVongKhac.setBackground(new java.awt.Color(255, 255, 255));
        jtfNoiTuVongKhac.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jtfNoiTuVongKhac.setForeground(new java.awt.Color(20, 20, 20));
        jtfNoiTuVongKhac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jtfNoiTuVongKhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNoiTuVongKhacActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/da/qlf0/images/floppy-disk.png"))); // NOI18N
        jButton1.setText("Lưu kết quả");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/da/qlf0/images/printer.png"))); // NOI18N
        jButton2.setText("Xuất bệnh án");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 1645, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 1630, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel19)
                                                .addComponent(jLabel21)
                                                .addComponent(jLabel22))
                                            .addGap(109, 109, 109)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jdcNgayNhapVien, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(74, 74, 74)
                                                    .addComponent(jLabel20)
                                                    .addGap(40, 40, 40)
                                                    .addComponent(jtfTTkhiNV, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jtfLuuY, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                                                    .addComponent(jtfTenCSNV, javax.swing.GroupLayout.Alignment.LEADING))))
                                        .addComponent(jLabel12)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel23)
                                                .addComponent(jLabel24))
                                            .addGap(144, 144, 144)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jdcNgayTuVong, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                                .addComponent(jcobNoiTuVong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(86, 86, 86)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel25)
                                                .addComponent(jLabel26))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jrbLiDoTV_BenhNen)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jrbLiDoTV_Covid)
                                                    .addGap(71, 71, 71)
                                                    .addComponent(jLabel27)
                                                    .addGap(34, 34, 34)
                                                    .addComponent(jtfLidoTuVongKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jtfNoiTuVongKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1766, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel15))
                                        .addGap(99, 99, 99)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jrbHTCL)
                                                .addGap(51, 51, 51)
                                                .addComponent(jrbCN_NV)
                                                .addGap(62, 62, 62)
                                                .addComponent(jrbTuVong)
                                                .addGap(71, 71, 71)
                                                .addComponent(jrbKhac))
                                            .addComponent(jtfKhacCuThe, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(62, 62, 62)
                                        .addComponent(jdc_NgayKTCL, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(jLabel17)
                                        .addGap(50, 50, 50)
                                        .addComponent(jdc_NgayXNAT, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)
                                        .addComponent(jLabel18)
                                        .addGap(71, 71, 71)
                                        .addComponent(jrbTestNhanh)
                                        .addGap(64, 64, 64)
                                        .addComponent(jrbPCR)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(585, 585, 585)
                .addComponent(jButton1)
                .addGap(116, 116, 116)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jrbCN_NV)
                    .addComponent(jrbHTCL)
                    .addComponent(jrbTuVong)
                    .addComponent(jrbKhac))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtfKhacCuThe, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jdc_NgayKTCL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(jrbTestNhanh)
                                .addComponent(jrbPCR)))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel11))
                    .addComponent(jdc_NgayXNAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jdcNgayNhapVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jtfTTkhiNV, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel22)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfTenCSNV, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfLuuY, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jdcNgayTuVong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jcobNoiTuVong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel25)
                                .addComponent(jtfNoiTuVongKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(jrbLiDoTV_BenhNen)
                        .addComponent(jrbLiDoTV_Covid)
                        .addComponent(jLabel27)
                        .addComponent(jtfLidoTuVongKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfKhacCuTheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfKhacCuTheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfKhacCuTheActionPerformed

    private void jtfTTkhiNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTTkhiNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTTkhiNVActionPerformed

    private void jrbCN_NVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCN_NVActionPerformed
        // TODO add your handling code here:
           
        jdc_NgayKTCL.setEnabled(true);
        jdc_NgayXNAT.setEnabled(true);
        jrbTestNhanh.setEnabled(true);
        jrbPCR.setEnabled(true);
        
        
        jtfKhacCuThe.setEnabled(true);
        
        jdcNgayNhapVien.setEnabled(true);
        jtfTTkhiNV.setEnabled(true);
        jtfTenCSNV.setEnabled(true);
        jtfLuuY.setEnabled(true);
        
        jdcNgayTuVong.setEnabled(false);
        jcobNoiTuVong.setEnabled(false);
        jtfNoiTuVongKhac.setEnabled(false);
        jtfLidoTuVongKhac.setEnabled(false);
        
        jrbLiDoTV_BenhNen.setEnabled(false);
        jrbLiDoTV_Covid.setEnabled(false);
    }//GEN-LAST:event_jrbCN_NVActionPerformed

    private void jrbHTCLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbHTCLActionPerformed
        // TODO add your handling code here:
        
        //true
        jdc_NgayKTCL.setEnabled(true);
        jdc_NgayXNAT.setEnabled(true);
        jrbTestNhanh.setEnabled(true);
        jrbPCR.setEnabled(true);
//        jDatePicker1.setEnabled(false);
//        jdcNgayNhapVien.setVisible(false);
        //false
        jtfKhacCuThe.setEnabled(true);
        
        jdcNgayNhapVien.setEnabled(false);
        jtfTTkhiNV.setEnabled(false);
        jtfTenCSNV.setEnabled(false);
        jtfLuuY.setEnabled(false);
        
        jdcNgayTuVong.setEnabled(false);
        jcobNoiTuVong.setEnabled(false);
        jtfNoiTuVongKhac.setEnabled(false);
        jtfLidoTuVongKhac.setEnabled(false);
        
        jrbLiDoTV_BenhNen.setEnabled(false);
        jrbLiDoTV_Covid.setEnabled(false);
//        jdc_NgayXNAT.setEnabled(false);
//        jrbTestNhanh.setEnabled(false);
//        jrbPCR.setEnabled(false);
        
       
    }//GEN-LAST:event_jrbHTCLActionPerformed

    private void jrbTuVongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTuVongActionPerformed
        // TODO add your handling code here:
           
        jdc_NgayKTCL.setEnabled(false);
        jdc_NgayXNAT.setEnabled(false);
        jrbTestNhanh.setEnabled(false);
        jrbPCR.setEnabled(false);
        
        
       
        jtfKhacCuThe.setEnabled(true);
        
        jdcNgayNhapVien.setEnabled(false);
        jtfTTkhiNV.setEnabled(false);
        jtfTenCSNV.setEnabled(false);
        jtfLuuY.setEnabled(false);
        
        jdcNgayTuVong.setEnabled(true);
        jcobNoiTuVong.setEnabled(true);
        jtfNoiTuVongKhac.setEnabled(true);
        jtfLidoTuVongKhac.setEnabled(true);
        
        jrbLiDoTV_BenhNen.setEnabled(true);
        jrbLiDoTV_Covid.setEnabled(true);
    }//GEN-LAST:event_jrbTuVongActionPerformed

    private void jrbKhacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbKhacActionPerformed
        // TODO add your handling code here:
        
               
        jdc_NgayKTCL.setEnabled(false);
        jdc_NgayXNAT.setEnabled(false);
        jrbTestNhanh.setEnabled(false);
        jrbPCR.setEnabled(false);
        
        
       
        jtfKhacCuThe.setEnabled(true);
        
        jdcNgayNhapVien.setEnabled(false);
        jtfTTkhiNV.setEnabled(false);
        jtfTenCSNV.setEnabled(false);
        jtfLuuY.setEnabled(false);
        
        jdcNgayTuVong.setEnabled(false);
        jcobNoiTuVong.setEnabled(false);
        jtfNoiTuVongKhac.setEnabled(false);
        jtfLidoTuVongKhac.setEnabled(false);
        
        jrbLiDoTV_BenhNen.setEnabled(false);
        jrbLiDoTV_Covid.setEnabled(false);
        
    }//GEN-LAST:event_jrbKhacActionPerformed

    private void jrbTestNhanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTestNhanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbTestNhanhActionPerformed

    private void jrbPCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPCRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbPCRActionPerformed

    private void jtfLuuYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfLuuYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfLuuYActionPerformed

    private void jtfTenCSNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTenCSNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTenCSNVActionPerformed

    private void jtfLidoTuVongKhacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfLidoTuVongKhacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfLidoTuVongKhacActionPerformed

    private void jrbLiDoTV_BenhNenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbLiDoTV_BenhNenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbLiDoTV_BenhNenActionPerformed

    private void jrbLiDoTV_CovidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbLiDoTV_CovidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbLiDoTV_CovidActionPerformed

    private void jtfNoiTuVongKhacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNoiTuVongKhacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNoiTuVongKhacActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.frame2.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        JFrame framex = new JFrame();
        String[] options = new String[2];
        options[0] = "Có";
        options[1] = "Không";
        int dialogButton = JOptionPane.YES_NO_OPTION;
        
        
        int dialogResult = JOptionPane.showOptionDialog(framex.getContentPane(), "Bạn muốn lưu thông tin kết quả điều trị?", "Lưu thông tin Kết quả điều trị", 0, JOptionPane.INFORMATION_MESSAGE, null, options, dialogButton);
        
        if(dialogResult == 0) {
            TaoKQDieuTriController kq = new TaoKQDieuTriController(this.MABN,
                    jcobNoiTuVong,
                    jdcNgayNhapVien,
                    jdcNgayTuVong,
                    jdc_NgayKTCL,
                    jdc_NgayXNAT,
                    jrbCN_NV,
                    jrbHTCL,
                    jrbKhac, 
                    jrbLiDoTV_BenhNen, 
                    jrbLiDoTV_Covid,
                    jrbPCR,
                    jrbTestNhanh,
                    jrbTuVong,
                    jtfKhacCuThe,
                    jtfLidoTuVongKhac,
                    jtfLuuY, 
                    jtfNoiTuVongKhac,
                    jtfTTkhiNV, 
                    jtfTenCSNV);
            
            try {
                if(kq.check_KQDT()==0){
                    kq.setDateToKQDieuTri();
                     JFrame frame3 = new JFrame();
                        frame3.setBounds(0,0,100,50);
                        JOptionPane.showMessageDialog(frame3,
                                "Thêm thành công kết quả điều trị");
                }else{
                    int dialogResult2 = JOptionPane.showOptionDialog(framex.getContentPane(), "Bệnh nhân đã có kết quả điều trị! Bạn muốn cập nhật mới thông tin ?", "Cập nhật Kết quả điều trị", 0, JOptionPane.INFORMATION_MESSAGE, null, options, dialogButton);
                     if(dialogResult2 == 0) {
                        kq.setDateToKQDieuTri_Update();
                        JFrame frame3 = new JFrame();
                        frame3.setBounds(0,0,100,50);
                        JOptionPane.showMessageDialog(frame3,
                                "Cập nhật thành công kết quả điều trị");
                     }
                    
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(KQDieuTri.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(KQDieuTri.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(KQDieuTri.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         JFrame framex = new JFrame();
        String[] options = new String[2];
        options[0] = "Có";
        options[1] = "Không";
        int dialogButton = JOptionPane.YES_NO_OPTION;
        
        
        int dialogResult = JOptionPane.showOptionDialog(framex.getContentPane(), "Xác nhận xuất bệnh án?", "Tạo bệnh án", 0, JOptionPane.INFORMATION_MESSAGE, null, options, dialogButton);
        
        if(dialogResult == 0) {
            TaoKQDieuTriController kq = new TaoKQDieuTriController(this.MABN,
                    jcobNoiTuVong,
                    jdcNgayNhapVien,
                    jdcNgayTuVong,
                    jdc_NgayKTCL,
                    jdc_NgayXNAT,
                    jrbCN_NV,
                    jrbHTCL,
                    jrbKhac, 
                    jrbLiDoTV_BenhNen, 
                    jrbLiDoTV_Covid,
                    jrbPCR,
                    jrbTestNhanh,
                    jrbTuVong,
                    jtfKhacCuThe,
                    jtfLidoTuVongKhac,
                    jtfLuuY, 
                    jtfNoiTuVongKhac,
                    jtfTTkhiNV, 
                    jtfTenCSNV);
             try {
                 if(kq.check_KQDT()==1){
                     PrintBenhAnController in =new PrintBenhAnController(this.MABN);
                     in.InBenhAn();
                 }else{
                     JFrame frame3 = new JFrame();
                        frame3.setBounds(0,0,100,50);
                        JOptionPane.showMessageDialog(frame3,
                                "Bệnh nhân chưa có kết quả điều trị tại nhà! Vui lòng tạo kết quả điều trị!");
                 }
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(KQDieuTri.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
                 Logger.getLogger(KQDieuTri.class.getName()).log(Level.SEVERE, null, ex);
                 JFrame frame3 = new JFrame();
                        frame3.setBounds(0,0,100,50);
                        JOptionPane.showMessageDialog(frame3,
                                "Lỗi xảy ra ! Vui lòng cập nhật các thông tin liên quan hoặc kiểm tra lại thông tin ");
             }
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bntG_TinhTrang;
    private javax.swing.ButtonGroup btnG_LiDoTV;
    private javax.swing.ButtonGroup btnG_LoaiXN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JComboBox<String> jcobNoiTuVong;
    private com.toedter.calendar.JDateChooser jdcNgayNhapVien;
    private com.toedter.calendar.JDateChooser jdcNgayTuVong;
    private com.toedter.calendar.JDateChooser jdc_NgayKTCL;
    private com.toedter.calendar.JDateChooser jdc_NgayXNAT;
    private javax.swing.JRadioButton jrbCN_NV;
    private javax.swing.JRadioButton jrbHTCL;
    private javax.swing.JRadioButton jrbKhac;
    private javax.swing.JRadioButton jrbLiDoTV_BenhNen;
    private javax.swing.JRadioButton jrbLiDoTV_Covid;
    private javax.swing.JRadioButton jrbPCR;
    private javax.swing.JRadioButton jrbTestNhanh;
    private javax.swing.JRadioButton jrbTuVong;
    private javax.swing.JTextField jtfKhacCuThe;
    private javax.swing.JTextField jtfLidoTuVongKhac;
    private javax.swing.JTextField jtfLuuY;
    private javax.swing.JTextField jtfNoiTuVongKhac;
    private javax.swing.JTextField jtfTTkhiNV;
    private javax.swing.JTextField jtfTenCSNV;
    // End of variables declaration//GEN-END:variables
}
