/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.da.qlf0.view.BenhNhan_Frame;

import com.da.qlf0.view.CapNhat.*;
import com.da.qlf0.view.GUI_ThemBN.*;
import com.toedter.calendar.JDateChooser;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;

/**
 *
 * @author Minh Cuong
 */
public class TTCaNhan_Vaccine extends javax.swing.JPanel {

    /**
     * Creates new form TTCoBan_ThemBN
     */
    public TTCaNhan_Vaccine() {
        initComponents();
        
    }

    public JComboBox<String> getJcobTiemVX_1() {
        return jcobTiemVX_1;
    }

    public JComboBox<String> getJcobTiemVX_2() {
        return jcobTiemVX_2;
    }

    public JComboBox<String> getJcobTiemVX_3() {
        return jcobTiemVX_3;
    }

    public JDateChooser getJdcTGMui1() {
        return jdcTGMui1;
    }

    public JDateChooser getJdcTGMui2() {
        return jdcTGMui2;
    }

    public JDateChooser getJdcTGMui3() {
        return jdcTGMui3;
    }

    public JRadioButton getJrbChuaTiem() {
        return jrbChuaTiem;
    }

    public JRadioButton getJrbTiem1Mui() {
        return jrbTiem1Mui;
    }

    public JRadioButton getJrbTiem2Mui() {
        return jrbTiem2Mui;
    }

    public JRadioButton getJrbTiem3Mui() {
        return jrbTiem3Mui;
    }

    public JRadioButton getJrbTiem_KhongBiet() {
        return jrbTiem_KhongBiet;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnG_MuiTiem = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jrbChuaTiem = new javax.swing.JRadioButton();
        jrbTiem1Mui = new javax.swing.JRadioButton();
        jrbTiem3Mui = new javax.swing.JRadioButton();
        jrbTiem2Mui = new javax.swing.JRadioButton();
        jrbTiem_KhongBiet = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jcobTiemVX_1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jdcTGMui1 = new com.toedter.calendar.JDateChooser();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcobTiemVX_2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jdcTGMui2 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jcobTiemVX_3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jdcTGMui3 = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(20, 20, 20));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(20, 20, 20));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 41, 102));
        jLabel9.setText("Mũi 1");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(20, 20, 20));
        jLabel12.setText(" Tình trạng tiêm Vắc xin:");

        jrbChuaTiem.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MuiTiem.add(jrbChuaTiem);
        jrbChuaTiem.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbChuaTiem.setForeground(new java.awt.Color(20, 20, 20));
        jrbChuaTiem.setText("Chưa tiêm");
        jrbChuaTiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbChuaTiemActionPerformed(evt);
            }
        });

        jrbTiem1Mui.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MuiTiem.add(jrbTiem1Mui);
        jrbTiem1Mui.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbTiem1Mui.setForeground(new java.awt.Color(20, 20, 20));
        jrbTiem1Mui.setText("1 Mũi");
        jrbTiem1Mui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTiem1MuiActionPerformed(evt);
            }
        });

        jrbTiem3Mui.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MuiTiem.add(jrbTiem3Mui);
        jrbTiem3Mui.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbTiem3Mui.setForeground(new java.awt.Color(20, 20, 20));
        jrbTiem3Mui.setText("3 Mũi");
        jrbTiem3Mui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTiem3MuiActionPerformed(evt);
            }
        });

        jrbTiem2Mui.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MuiTiem.add(jrbTiem2Mui);
        jrbTiem2Mui.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbTiem2Mui.setForeground(new java.awt.Color(20, 20, 20));
        jrbTiem2Mui.setText("2 Mũi");
        jrbTiem2Mui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTiem2MuiActionPerformed(evt);
            }
        });

        jrbTiem_KhongBiet.setBackground(new java.awt.Color(255, 255, 255));
        btnG_MuiTiem.add(jrbTiem_KhongBiet);
        jrbTiem_KhongBiet.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jrbTiem_KhongBiet.setForeground(new java.awt.Color(20, 20, 20));
        jrbTiem_KhongBiet.setText("Không biết");
        jrbTiem_KhongBiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTiem_KhongBietActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(166, 166, 166));

        jcobTiemVX_1.setBackground(new java.awt.Color(255, 255, 255));
        jcobTiemVX_1.setForeground(new java.awt.Color(20, 20, 20));
        jcobTiemVX_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AstraZeneca", "Sputnik V", "VeroCell", "Pfizer", "Moderna", "Janssen", "Covaxin" }));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(20, 20, 20));
        jLabel1.setText("Thời gian tiêm: *");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 20, 20));
        jLabel2.setText("Loại Vắc xin 1: *");

        jdcTGMui1.setBackground(new java.awt.Color(255, 255, 255));
        jdcTGMui1.setForeground(new java.awt.Color(20, 20, 20));
        jdcTGMui1.setDateFormatString("dd-MM-yyyy\n");

        jSeparator5.setBackground(new java.awt.Color(166, 166, 166));

        jSeparator6.setBackground(new java.awt.Color(166, 166, 166));

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 41, 102));
        jLabel11.setText("Mũi 2");

        jSeparator7.setBackground(new java.awt.Color(166, 166, 166));

        jSeparator4.setBackground(new java.awt.Color(166, 166, 166));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 1766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel12)
                            .addGap(75, 75, 75)
                            .addComponent(jrbChuaTiem)
                            .addGap(60, 60, 60)
                            .addComponent(jrbTiem1Mui)
                            .addGap(83, 83, 83)
                            .addComponent(jrbTiem2Mui)
                            .addGap(73, 73, 73)
                            .addComponent(jrbTiem3Mui)
                            .addGap(60, 60, 60)
                            .addComponent(jrbTiem_KhongBiet))
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1766, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addComponent(jLabel9))
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 1766, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addComponent(jLabel2)
                            .addGap(93, 93, 93)
                            .addComponent(jcobTiemVX_1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(170, 170, 170)
                            .addComponent(jLabel1)
                            .addGap(119, 119, 119)
                            .addComponent(jdcTGMui1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addComponent(jLabel11))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jrbChuaTiem)
                    .addComponent(jrbTiem1Mui)
                    .addComponent(jrbTiem2Mui)
                    .addComponent(jrbTiem3Mui)
                    .addComponent(jrbTiem_KhongBiet))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jcobTiemVX_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jdcTGMui1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(20, 20, 20));
        jLabel7.setText("TIÊM VẮC XIN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(466, 466, 466)
                .addComponent(jLabel7)
                .addContainerGap(1152, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 41, 102));
        jLabel8.setText("TIÊM VẮC XIN PHÒNG COVID-19");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(20, 20, 20));
        jLabel3.setText("Loại Vắc xin 2: *");

        jcobTiemVX_2.setBackground(new java.awt.Color(255, 255, 255));
        jcobTiemVX_2.setForeground(new java.awt.Color(20, 20, 20));
        jcobTiemVX_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AstraZeneca", "Sputnik V", "VeroCell", "Pfizer", "Moderna", "Janssen", "Covaxin" }));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(20, 20, 20));
        jLabel4.setText("Thời gian tiêm: *");

        jdcTGMui2.setBackground(new java.awt.Color(255, 255, 255));
        jdcTGMui2.setForeground(new java.awt.Color(20, 20, 20));
        jdcTGMui2.setDateFormatString("dd-MM-yyyy\n");

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 41, 102));
        jLabel13.setText("Mũi 3");

        jSeparator8.setBackground(new java.awt.Color(166, 166, 166));

        jSeparator9.setBackground(new java.awt.Color(166, 166, 166));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(20, 20, 20));
        jLabel5.setText("Loại Vắc xin 3: *");

        jcobTiemVX_3.setBackground(new java.awt.Color(255, 255, 255));
        jcobTiemVX_3.setForeground(new java.awt.Color(20, 20, 20));
        jcobTiemVX_3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AstraZeneca", "Sputnik V", "VeroCell", "Pfizer", "Moderna", "Janssen", "Covaxin" }));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(20, 20, 20));
        jLabel6.setText("Thời gian tiêm : *");

        jdcTGMui3.setBackground(new java.awt.Color(255, 255, 255));
        jdcTGMui3.setForeground(new java.awt.Color(20, 20, 20));
        jdcTGMui3.setDateFormatString("dd-MM-yyyy\n");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel3)
                                .addGap(102, 102, 102)
                                .addComponent(jcobTiemVX_2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163)
                                .addComponent(jLabel4)
                                .addGap(128, 128, 128)
                                .addComponent(jdcTGMui2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel5)
                                .addGap(107, 107, 107)
                                .addComponent(jcobTiemVX_3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(165, 165, 165)
                                .addComponent(jLabel6)
                                .addGap(128, 128, 128)
                                .addComponent(jdcTGMui3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 83, Short.MAX_VALUE))
                            .addComponent(jSeparator8))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jcobTiemVX_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jdcTGMui2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcobTiemVX_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jdcTGMui3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrbTiem_KhongBietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTiem_KhongBietActionPerformed
        // TODO add your handling code here:
        
        jcobTiemVX_1.setEnabled(false);
        jcobTiemVX_2.setEnabled(false);
        jcobTiemVX_3.setEnabled(false);
    }//GEN-LAST:event_jrbTiem_KhongBietActionPerformed

    private void jrbChuaTiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbChuaTiemActionPerformed
        // TODO add your handling code here:
        
        jcobTiemVX_1.setEnabled(true);
        jcobTiemVX_2.setEnabled(false);
        jcobTiemVX_3.setEnabled(false);
    }//GEN-LAST:event_jrbChuaTiemActionPerformed

    private void jrbTiem1MuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTiem1MuiActionPerformed
        // TODO add your handling code here:
        jcobTiemVX_1.setEnabled(true);
        jcobTiemVX_2.setEnabled(false);
        jcobTiemVX_3.setEnabled(false);
    }//GEN-LAST:event_jrbTiem1MuiActionPerformed

    private void jrbTiem2MuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTiem2MuiActionPerformed
        // TODO add your handling code here:
          jcobTiemVX_1.setEnabled(true);
        jcobTiemVX_2.setEnabled(true);
        jcobTiemVX_3.setEnabled(false);
    }//GEN-LAST:event_jrbTiem2MuiActionPerformed

    private void jrbTiem3MuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTiem3MuiActionPerformed
        // TODO add your handling code here:
          jcobTiemVX_1.setEnabled(true);
        jcobTiemVX_2.setEnabled(true);
        jcobTiemVX_3.setEnabled(true);
    }//GEN-LAST:event_jrbTiem3MuiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnG_MuiTiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JComboBox<String> jcobTiemVX_1;
    private javax.swing.JComboBox<String> jcobTiemVX_2;
    private javax.swing.JComboBox<String> jcobTiemVX_3;
    private com.toedter.calendar.JDateChooser jdcTGMui1;
    private com.toedter.calendar.JDateChooser jdcTGMui2;
    private com.toedter.calendar.JDateChooser jdcTGMui3;
    private javax.swing.JRadioButton jrbChuaTiem;
    private javax.swing.JRadioButton jrbTiem1Mui;
    private javax.swing.JRadioButton jrbTiem2Mui;
    private javax.swing.JRadioButton jrbTiem3Mui;
    private javax.swing.JRadioButton jrbTiem_KhongBiet;
    // End of variables declaration//GEN-END:variables
}
