/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.da.qlf0.view.BenhNhan_Frame;

import com.da.qlf0.bean.DanhMucTTCaNhan;
import com.da.qlf0.controller.ChuyenMH_ThongTinCaNhan;
import java.util.ArrayList;

/**
 *
 * @author Minh Cuong
 */
public class TTCaNhan extends javax.swing.JPanel {

    /**
     * Creates new form TTCaNhan
     */
    public TTCaNhan() {
        initComponents();
        ChuyenMH_ThongTinCaNhan controller = new ChuyenMH_ThongTinCaNhan(jpnView);
        controller.setView(jpnTTCoBan,jlbTTCoBan);
        
        ArrayList<DanhMucTTCaNhan> listItem = new ArrayList<>();
        listItem.add(new DanhMucTTCaNhan("ThongTinCoBan",jpnTTCoBan,jlbTTCoBan));
        listItem.add(new DanhMucTTCaNhan("TiemVaccine",jpnTiemPhong,jlbTiemPhong));
        listItem.add(new DanhMucTTCaNhan("BenhNen",jpnBenhNen,jlbBenhNen));
        
        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnMenu = new javax.swing.JPanel();
        jpnTTCoBan = new javax.swing.JPanel();
        jlbTTCoBan = new javax.swing.JLabel();
        jpnTiemPhong = new javax.swing.JPanel();
        jlbTiemPhong = new javax.swing.JLabel();
        jpnBenhNen = new javax.swing.JPanel();
        jlbBenhNen = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();

        jpnMenu.setBackground(new java.awt.Color(255, 255, 255));

        jpnTTCoBan.setBackground(new java.awt.Color(0, 180, 153));

        jlbTTCoBan.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jlbTTCoBan.setText("Thông tin cơ bản");

        javax.swing.GroupLayout jpnTTCoBanLayout = new javax.swing.GroupLayout(jpnTTCoBan);
        jpnTTCoBan.setLayout(jpnTTCoBanLayout);
        jpnTTCoBanLayout.setHorizontalGroup(
            jpnTTCoBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTTCoBanLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jlbTTCoBan)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jpnTTCoBanLayout.setVerticalGroup(
            jpnTTCoBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTTCoBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTTCoBan, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnTiemPhong.setBackground(new java.awt.Color(0, 180, 153));

        jlbTiemPhong.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jlbTiemPhong.setText("Thông Tin Tiêm Phòng");

        javax.swing.GroupLayout jpnTiemPhongLayout = new javax.swing.GroupLayout(jpnTiemPhong);
        jpnTiemPhong.setLayout(jpnTiemPhongLayout);
        jpnTiemPhongLayout.setHorizontalGroup(
            jpnTiemPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTiemPhongLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jlbTiemPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jpnTiemPhongLayout.setVerticalGroup(
            jpnTiemPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbTiemPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpnBenhNen.setBackground(new java.awt.Color(0, 180, 153));

        jlbBenhNen.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jlbBenhNen.setText("Thông Tin Bệnh Nền");

        javax.swing.GroupLayout jpnBenhNenLayout = new javax.swing.GroupLayout(jpnBenhNen);
        jpnBenhNen.setLayout(jpnBenhNenLayout);
        jpnBenhNenLayout.setHorizontalGroup(
            jpnBenhNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBenhNenLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jlbBenhNen, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnBenhNenLayout.setVerticalGroup(
            jpnBenhNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBenhNenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbBenhNen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jpnTTCoBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnTiemPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnBenhNen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnTTCoBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnTiemPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnBenhNen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpnView.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbBenhNen;
    private javax.swing.JLabel jlbTTCoBan;
    private javax.swing.JLabel jlbTiemPhong;
    private javax.swing.JPanel jpnBenhNen;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnTTCoBan;
    private javax.swing.JPanel jpnTiemPhong;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}
